import { OpportunityType, RemoteType } from '../generated/prisma/enums';

export interface IndianCatalogOpportunity {
  companyName: string;
  companyWebsite: string;
  industry: string;
  title: string;
  type: OpportunityType;
  location: string;
  remoteType: RemoteType;
  salaryRange: string;
  benefits?: string;
  applicationUrl: string;
  deadline: Date;
  description: string;
  requirements: string;
  tags: string[];
}

export const INDIAN_TECH_CATALOG: IndianCatalogOpportunity[] = [
  // ==========================================
  // 1. TIER-1 TECH & PRODUCT MNCs (INDIA HUBS)
  // ==========================================
  {
    companyName: 'Google',
    companyWebsite: 'https://careers.google.com',
    industry: 'Technology & Cloud',
    title: 'Software Engineering Intern, Summer 2027',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,25,000 - ₹1,50,000 / month',
    benefits: 'High PPO conversion, gourmet meals, shuttle service, health insurance',
    applicationUrl: 'https://careers.google.com/jobs/results/software-engineering-intern-bangalore/',
    deadline: new Date('2026-12-15'),
    description: 'Work on core Google products including Google Search, Android, Google Pay India, and Google Cloud platform services.',
    requirements: 'Enrolled in Bachelor or Master CS/IT degree in India graduating in 2027 or 2028. Strong Data Structures, Algorithms, C++, Java, or Python.',
    tags: ['google', 'internship', 'bengaluru', 'swe', 'algorithms', 'india'],
  },
  {
    companyName: 'Google',
    companyWebsite: 'https://careers.google.com',
    industry: 'Technology & Cloud',
    title: 'STEP Internship 2027 (Student Training in Engineering Program)',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹85,000 - ₹1,15,000 / month',
    benefits: 'Relocation assistance, mentorship, return offer pathway, learning stipends',
    applicationUrl: 'https://buildyourfuture.withgoogle.com/step',
    deadline: new Date('2026-11-30'),
    description: 'Developmental software internship for 1st & 2nd year undergraduate students across India with direct mentorship from Google Engineers.',
    requirements: 'Currently enrolled in an undergraduate degree in Computer Science or related field in India; graduating in 2028 or 2029.',
    tags: ['google', 'step', 'internship', 'hyderabad', 'first-year', 'second-year', 'india'],
  },
  {
    companyName: 'Google',
    companyWebsite: 'https://careers.google.com',
    industry: 'Technology & Cloud',
    title: 'Cloud Technical Solutions Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,00,000 / month',
    benefits: 'Google Cloud certification vouchers, mentorship, housing assistance',
    applicationUrl: 'https://careers.google.com/jobs/results/cloud-technical-solutions-intern',
    deadline: new Date('2026-12-05'),
    description: 'Diagnose and resolve complex architectural challenges on Google Cloud Platform (GCP) including BigQuery, Kubernetes Engine, and IAM.',
    requirements: 'Pursuing Bachelor’s or Master’s in Computer Science/IT/ECE in India. Strong networking, Linux, and scripting in Python or Go.',
    tags: ['google', 'gcp', 'cloud', 'internship', 'bengaluru', 'linux', 'india'],
  },
  {
    companyName: 'Microsoft',
    companyWebsite: 'https://careers.microsoft.com',
    industry: 'Technology & Cloud',
    title: 'Software Engineering Intern - Microsoft India Development Center (IDC)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,25,000 / month',
    benefits: 'Housing allowance, wellness reimbursement, Microsoft Surface hardware, medical coverage',
    applicationUrl: 'https://careers.microsoft.com/us/en/job/1689234/software-engineering-intern',
    deadline: new Date('2026-11-20'),
    description: 'Build enterprise cloud architectures, generative AI copilots, and distributed systems powering Microsoft Azure and Office 365.',
    requirements: 'Pursuing B.Tech/M.Tech/Dual Degree in CS/IT or relevant engineering discipline in India. Strong C++, C#, Java, or Python foundations.',
    tags: ['microsoft', 'idc', 'internship', 'bengaluru', 'azure', 'copilot', 'india'],
  },
  {
    companyName: 'Microsoft',
    companyWebsite: 'https://careers.microsoft.com',
    industry: 'Technology & Cloud',
    title: 'Software Engineering Intern - Cloud & AI Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,25,000 / month',
    benefits: 'Cab transport, fitness perks, relocation allowance, high PPO conversion',
    applicationUrl: 'https://careers.microsoft.com/us/en/job/1689235/software-engineering-intern-hyderabad',
    deadline: new Date('2026-11-25'),
    description: 'Work on hyper-scale infrastructure, security services, and developer tooling at Microsoft IDC Hyderabad campus.',
    requirements: 'B.Tech / M.Tech students graduating in 2027 or 2028. Strong algorithm problem-solving skills.',
    tags: ['microsoft', 'internship', 'hyderabad', 'cloud', 'ai', 'india'],
  },
  {
    companyName: 'Microsoft',
    companyWebsite: 'https://careers.microsoft.com',
    industry: 'Technology & Cloud',
    title: 'Data & Applied Sciences Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Noida, Uttar Pradesh, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,30,000 / month',
    benefits: 'Relocation assistance, Azure OpenAI compute quota, high PPO conversion',
    applicationUrl: 'https://careers.microsoft.com/us/en/job/1689240/data-scientist-intern-noida',
    deadline: new Date('2026-12-01'),
    description: 'Build machine learning models, search ranking pipelines for Bing, and LLM fine-tuning pipelines for Copilot services.',
    requirements: 'Master or Bachelor student in CS, Data Science, or Math in India. Proficiency in Python, PyTorch, and statistics.',
    tags: ['microsoft', 'data-science', 'internship', 'noida', 'delhi-ncr', 'ai', 'india'],
  },
  {
    companyName: 'Amazon',
    companyWebsite: 'https://amazon.jobs',
    industry: 'E-Commerce & Cloud',
    title: 'Software Development Engineer (SDE) Intern - Summer 2027',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,10,000 / month',
    benefits: 'Housing allowance, round-trip travel reimbursement, Amazon Prime, high return offer rate',
    applicationUrl: 'https://amazon.jobs/en/jobs/2589012/software-development-engineer-intern',
    deadline: new Date('2026-11-30'),
    description: 'Design and build high-throughput backend services powering AWS cloud, Amazon.in retail platform, and Alexa Voice AI.',
    requirements: 'Enrolled in an Indian university degree in Computer Science; graduation in 2027 or 2028. Strong Java, C++, or Go.',
    tags: ['amazon', 'sde', 'internship', 'bengaluru', 'aws', 'backend', 'india'],
  },
  {
    companyName: 'Amazon',
    companyWebsite: 'https://amazon.jobs',
    industry: 'E-Commerce & Cloud',
    title: 'Software Development Engineer (SDE) Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,10,000 / month',
    benefits: 'Housing stipend, meal coupons, relocation assistance, PPO track',
    applicationUrl: 'https://amazon.jobs/en/jobs/2589013/software-development-engineer-intern-hyderabad',
    deadline: new Date('2026-12-05'),
    description: 'Build automated supply chain optimization models, logistics engines, and payment gateways for global and Indian customers.',
    requirements: 'B.Tech/BE/M.Tech students in India graduating 2027/2028. Solid grasp of OOP, OS, and DBMS concepts.',
    tags: ['amazon', 'sde', 'internship', 'hyderabad', 'java', 'india'],
  },
  {
    companyName: 'Amazon',
    companyWebsite: 'https://amazon.jobs',
    industry: 'E-Commerce & Cloud',
    title: 'Data Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹95,000 / month',
    benefits: 'Transport allowance, meal vouchers, AWS certifications sponsorship',
    applicationUrl: 'https://amazon.jobs/en/jobs/data-engineer-intern-chennai',
    deadline: new Date('2026-11-28'),
    description: 'Design and scale big data pipelines, Redshift data warehouses, and Spark ETL streaming pipelines processing petabytes of consumer analytics.',
    requirements: 'Pursuing CS/IT/Data Engineering in India. Strong SQL, Python, Spark, and data modeling concepts.',
    tags: ['amazon', 'data-engineering', 'internship', 'chennai', 'sql', 'spark', 'india'],
  },
  {
    companyName: 'Apple',
    companyWebsite: 'https://apple.com/careers',
    industry: 'Consumer Tech & Hardware',
    title: 'Software Engineering Intern - Maps & Core OS',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,20,000 / month',
    benefits: 'Apple product discounts, relocation assistance, health coverage, executive mentorship',
    applicationUrl: 'https://jobs.apple.com/en-in/details/200542312/software-engineering-intern',
    deadline: new Date('2026-11-28'),
    description: 'Work with the Apple Maps and Core OS engineering teams in Hyderabad on geospatial algorithms, routing graph pipelines, and iOS frameworks.',
    requirements: 'Enrolled in Computer Science or related degree in India. Strong C++, Swift, Python, and data structures proficiency.',
    tags: ['apple', 'internship', 'hyderabad', 'maps', 'c++', 'swift', 'india'],
  },
  {
    companyName: 'Meta',
    companyWebsite: 'https://metacareers.com',
    industry: 'Social Tech & AI',
    title: 'Software Engineering Intern - Infrastructure & Network Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,50,000 / month',
    benefits: 'Meta Quest device, housing stipend, free gourmet meals, return offer pathway',
    applicationUrl: 'https://metacareers.com/jobs/software-engineering-intern-india',
    deadline: new Date('2026-11-30'),
    description: 'Build hyper-scale network infrastructure, content delivery caching, and datacenter telemetry supporting WhatsApp, Instagram, and Facebook.',
    requirements: 'Pursuing Computer Science or related degree in India. Strong C++, Python, Linux networking, and distributed systems.',
    tags: ['meta', 'internship', 'bengaluru', 'infrastructure', 'c++', 'networking', 'india'],
  },
  {
    companyName: 'Adobe',
    companyWebsite: 'https://adobe.com/careers',
    industry: 'Creative & Digital Software',
    title: 'Software Development Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Noida, Uttar Pradesh, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,00,000 / month',
    benefits: 'Creative Cloud subscription, wellness reimbursement, shuttle transport, PPO conversion',
    applicationUrl: 'https://adobe.wd5.myworkdayjobs.com/adobe-careers/job/Noida/SDE-Intern',
    deadline: new Date('2026-11-25'),
    description: 'Develop features for Adobe Creative Cloud, Acrobat Document Cloud, and Adobe Firefly generative AI tools.',
    requirements: 'B.Tech/Dual Degree students graduating 2027. Strong C++, Java, or Web technologies (WebAssembly, WebGL).',
    tags: ['adobe', 'internship', 'noida', 'delhi-ncr', 'c++', 'firefly', 'india'],
  },
  {
    companyName: 'Nvidia',
    companyWebsite: 'https://nvidia.com/careers',
    industry: 'AI, GPUs & Hardware',
    title: 'System Software Engineering Intern - GPU Computing & CUDA',
    type: OpportunityType.INTERNSHIP,
    location: 'Pune, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹95,000 - ₹1,20,000 / month',
    benefits: 'Nvidia stock purchase plan eligibility, high-end GPU workstations, mentorship',
    applicationUrl: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/India-Pune/Software-Intern',
    deadline: new Date('2026-11-18'),
    description: 'Optimize CUDA compilers, GPU device drivers, and AI acceleration runtimes (TensorRT) for LLM training and inference.',
    requirements: 'Pursuing Bachelor’s or Master’s in CS/ECE in India. Deep knowledge of C, C++, Computer Architecture, and Operating Systems.',
    tags: ['nvidia', 'internship', 'pune', 'cuda', 'c++', 'gpu', 'ai', 'india'],
  },
  {
    companyName: 'Nvidia',
    companyWebsite: 'https://nvidia.com/careers',
    industry: 'AI, GPUs & Hardware',
    title: 'Deep Learning Software Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,10,000 / month',
    benefits: 'DGX Cloud access, cutting-edge AI research environment, return offer pathway',
    applicationUrl: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/India-Bengaluru/Deep-Learning-Intern',
    deadline: new Date('2026-12-05'),
    description: 'Work on transformer architectures, NeMo framework, and AI model quantization for enterprise generative AI deployments.',
    requirements: 'Strong background in Deep Learning, PyTorch, CUDA, and high-performance Python/C++.',
    tags: ['nvidia', 'internship', 'bengaluru', 'deep-learning', 'pytorch', 'india'],
  },
  {
    companyName: 'Qualcomm',
    companyWebsite: 'https://qualcomm.com/careers',
    industry: 'Semiconductors & Wireless',
    title: 'Software Engineer Intern - Snapdragon AI & Modem Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹85,000 - ₹1,05,000 / month',
    benefits: 'Relocation allowance, comprehensive health cover, lab equipment access',
    applicationUrl: 'https://qualcomm.wd5.myworkdayjobs.com/External/job/Hyderabad-IND/Engineer-Intern',
    deadline: new Date('2026-11-30'),
    description: 'Design low-level software, 5G protocol stacks, and NPU firmware for Snapdragon mobile and automotive platforms.',
    requirements: 'B.Tech/M.Tech in CS/ECE/EEE in India. Proficiency in Embedded C, C++, Linux kernel, and Microcontrollers.',
    tags: ['qualcomm', 'internship', 'hyderabad', 'embedded', 'snapdragon', '5g', 'india'],
  },
  {
    companyName: 'Cisco',
    companyWebsite: 'https://cisco.com/careers',
    industry: 'Networking & Cybersecurity',
    title: 'Software Engineer Intern - Cloud & Network Security',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹90,000 - ₹1,10,000 / month',
    benefits: 'Fitness reimbursement, Cisco certifications coverage, hybrid flexibility',
    applicationUrl: 'https://jobs.cisco.com/jobs/SearchJobs/India-Software-Engineer-Intern',
    deadline: new Date('2026-12-10'),
    description: 'Build enterprise networking software, secure SD-WAN controllers, and cloud threat intelligence pipelines.',
    requirements: 'Enrolled in Computer Science/IT/ECE in India. Solid knowledge of TCP/IP, Computer Networks, Linux, and Python/Go/C++.',
    tags: ['cisco', 'internship', 'bengaluru', 'networking', 'security', 'python', 'india'],
  },
  {
    companyName: 'Intel',
    companyWebsite: 'https://intel.com/careers',
    industry: 'Semiconductors & Computing',
    title: 'Graduate Technical Intern - Silicon Architecture & Software',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹80,000 - ₹1,00,000 / month',
    benefits: 'Silicon design tools training, medical benefits, transport facilities',
    applicationUrl: 'https://jobs.intel.com/en/search-jobs/India/Intern',
    deadline: new Date('2026-11-20'),
    description: 'Validate hardware IP blocks, develop system firmware/BIOS, and write software benchmarks for Intel Xeon and Core processors.',
    requirements: 'Pursuing B.Tech/M.Tech in CS/ECE/VLSI in India. Knowledge of Verilog/VHDL, Python scripting, or C/C++.',
    tags: ['intel', 'internship', 'bengaluru', 'vlsi', 'silicon', 'c++', 'india'],
  },
  {
    companyName: 'AMD',
    companyWebsite: 'https://amd.com/careers',
    industry: 'Semiconductors & AI',
    title: 'Software Development Intern - ROCm & AI Software Ecosystem',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹85,000 - ₹1,05,000 / month',
    benefits: 'AMD hardware discounts, flexible work hours, learning allowance',
    applicationUrl: 'https://careers.amd.com/careers-home/jobs?keywords=intern&location=India',
    deadline: new Date('2026-11-28'),
    description: 'Contribute to AMD’s open-source ROCm GPU computing platform, PyTorch optimizations, and server AI accelerators.',
    requirements: 'Enrolled in Computer Science or Electrical Engineering in India. Strong C++, Python, and Linux systems background.',
    tags: ['amd', 'internship', 'hyderabad', 'rocm', 'gpu', 'ai', 'india'],
  },
  {
    companyName: 'Salesforce',
    companyWebsite: 'https://salesforce.com/careers',
    industry: 'Enterprise CRM & Cloud',
    title: 'Software Engineering Intern - Core Infrastructure',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,00,000 - ₹1,20,000 / month',
    benefits: 'Home office budget, comprehensive health benefits, volunteer time off, PPO opportunity',
    applicationUrl: 'https://salesforce.wd1.myworkdayjobs.com/External_Career_Site/job/India---Hyderabad/Software-Engineering-Intern',
    deadline: new Date('2026-11-15'),
    description: 'Build hyper-scale multi-tenant cloud architectures, database replication tools, and Einstein AI platform services.',
    requirements: 'Undergraduate student in CS/IT in India graduating in 2027. Strong Java, distributed systems, and SQL experience.',
    tags: ['salesforce', 'internship', 'hyderabad', 'java', 'cloud', 'einstein', 'india'],
  },
  {
    companyName: 'Intuit',
    companyWebsite: 'https://intuit.com/careers',
    industry: 'Financial Software',
    title: 'Software Engineering Intern (QuickBooks & TurboTax)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,15,000 / month',
    benefits: 'Health insurance, wellness stipend, free food and transport, return offer path',
    applicationUrl: 'https://jobs.intuit.com/job/bengaluru/software-engineer-intern',
    deadline: new Date('2026-11-30'),
    description: 'Work with the Intuit India development center building AI-driven fintech products serving millions of small businesses globally.',
    requirements: 'Pursuing Bachelor’s or Master’s in CS or related degree in India. Strong Java, Spring Boot, React, or Python skills.',
    tags: ['intuit', 'internship', 'bengaluru', 'fintech', 'java', 'react', 'india'],
  },
  {
    companyName: 'PayPal',
    companyWebsite: 'https://paypal.com/careers',
    industry: 'FinTech & Payments',
    title: 'Software Engineer Intern - Risk & Data Science',
    type: OpportunityType.INTERNSHIP,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹95,000 - ₹1,15,000 / month',
    benefits: 'Comprehensive health coverage, transportation, meal vouchers, PPO conversion',
    applicationUrl: 'https://paypal.wd1.myworkdayjobs.com/PayPal-Jobs/job/Chennai-India/Software-Engineer-Intern',
    deadline: new Date('2026-11-20'),
    description: 'Develop low-latency fraud detection algorithms, transaction risk engines, and secure payment tokenization microservices.',
    requirements: 'B.Tech/M.Tech CS students graduating in 2027. Strong programming in Java, Python, or Go and relational databases.',
    tags: ['paypal', 'internship', 'chennai', 'fintech', 'risk', 'fraud-detection', 'india'],
  },
  {
    companyName: 'Uber',
    companyWebsite: 'https://uber.com/careers',
    industry: 'Mobility & Logistics',
    title: 'Software Engineering Intern, Summer 2027',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,20,000 - ₹1,40,000 / month',
    benefits: 'Monthly Uber ride credits, housing allowance, health insurance, high PPO conversion',
    applicationUrl: 'https://uber.com/careers/internships-india',
    deadline: new Date('2026-11-25'),
    description: 'Build real-time dispatch matching engines, map intelligence systems, and payment infrastructure for Uber globally.',
    requirements: 'Undergraduate student in Computer Science graduating in 2027. Strong coding in Golang, Java, or Python and system design basics.',
    tags: ['uber', 'internship', 'hyderabad', 'golang', 'maps', 'distributed-systems', 'india'],
  },
  {
    companyName: 'Atlassian',
    companyWebsite: 'https://atlassian.com/careers',
    industry: 'Enterprise Software & Collaboration',
    title: 'Software Engineering Intern (India R&D Center)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹1,00,000 / month',
    benefits: 'Work from anywhere in India, home office setup budget, wellness allowance',
    applicationUrl: 'https://atlassian.com/careers/students',
    deadline: new Date('2026-11-20'),
    description: 'Build enterprise collaboration software including Jira, Confluence, and Loom used by millions of development teams globally.',
    requirements: 'Pursuing Bachelor’s or Master’s in Computer Science in India; graduating in 2027 or 2028. Experience with React, Java, or Kotlin.',
    tags: ['atlassian', 'internship', 'bengaluru', 'remote', 'react', 'java', 'india'],
  },
  {
    companyName: 'Goldman Sachs',
    companyWebsite: 'https://goldmansachs.com/careers',
    industry: 'Investment Banking & FinTech',
    title: 'Summer Analyst Engineering Intern 2027',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,00,000 - ₹1,25,000 / month',
    benefits: 'High PPO conversion to full-time Analyst, health coverage, executive mentorship',
    applicationUrl: 'https://goldmansachs.com/careers/students/programs/summer-analyst-program.html',
    deadline: new Date('2026-11-15'),
    description: 'Develop low-latency algorithmic trading systems, portfolio risk engines, and financial analytics platforms.',
    requirements: 'Penultimate year undergraduate or master student in India. Strong analytical skills, C++, Java, or Python, and DSA.',
    tags: ['goldman-sachs', 'internship', 'bengaluru', 'fintech', 'quantitative', 'algorithms', 'india'],
  },
  {
    companyName: 'Morgan Stanley',
    companyWebsite: 'https://morganstanley.com/careers',
    industry: 'Investment Banking & FinTech',
    title: 'Technology Summer Analyst Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹90,000 - ₹1,10,000 / month',
    benefits: 'Relocation assistance, comprehensive healthcare, financial modeling workshops',
    applicationUrl: 'https://morganstanley.com/careers/students-and-graduates',
    deadline: new Date('2026-11-22'),
    description: 'Build distributed cloud microservices, market data feeds, and wealth management software for global financial exchanges.',
    requirements: 'Pursuing Computer Science or related degree in India. Strong understanding of OOP, Data Structures, and SQL.',
    tags: ['morgan-stanley', 'internship', 'mumbai', 'fintech', 'java', 'sql', 'india'],
  },
  {
    companyName: 'JPMorgan Chase',
    companyWebsite: 'https://jpmorganchase.com/careers',
    industry: 'Banking & Financial Services',
    title: 'Software Engineer Summer Intern (SEP)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹85,000 - ₹1,05,000 / month',
    benefits: 'High PPO rate, learning & development allowances, medical insurance',
    applicationUrl: 'https://careers.jpmorgan.com/us/en/students/programs/software-engineer-summer-internship',
    deadline: new Date('2026-11-18'),
    description: 'Work on mission-critical payments processing, cybersecurity monitoring, and cloud-native financial applications.',
    requirements: 'B.Tech/BE students in India graduating in 2027. Strong Java, Spring, React, or Python and computer science fundamentals.',
    tags: ['jpmorgan', 'internship', 'bengaluru', 'fintech', 'java', 'spring', 'india'],
  },
  {
    companyName: 'DE Shaw',
    companyWebsite: 'https://deshaw.com',
    industry: 'Quantitative Hedge Fund & FinTech',
    title: 'Software Developer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,50,000 - ₹2,00,000 / month',
    benefits: 'Premium housing accommodation, daily gourmet dining, travel reimbursement, highest compensation tier',
    applicationUrl: 'https://deshawindia.com/careers',
    deadline: new Date('2026-11-10'),
    description: 'Build ultra-low-latency electronic trading platforms, quantitative modeling tools, and high-performance financial data engines.',
    requirements: 'Top-tier academic record in Computer Science, Math, or Physics in India. Exceptional Data Structures, Algorithms, and C++/Python.',
    tags: ['de-shaw', 'internship', 'hyderabad', 'quantitative', 'c++', 'high-frequency-trading', 'india'],
  },
  {
    companyName: 'Tower Research Capital',
    companyWebsite: 'https://tower-research.com',
    industry: 'High Frequency Trading',
    title: 'Quantitative Software Developer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,50,000 - ₹2,25,000 / month',
    benefits: 'Luxury guest house stay, round-trip airfare, PPO fast track, top-tier compensation',
    applicationUrl: 'https://tower-research.com/careers',
    deadline: new Date('2026-11-12'),
    description: 'Develop nanosecond-latency network drivers, Linux kernel bypass software, and real-time execution algorithms for global electronic markets.',
    requirements: 'Pursuing B.Tech/M.Tech in CS/EE in India. World-class mastery of modern C++ (C++20), lock-free programming, and CPU caches.',
    tags: ['tower-research', 'internship', 'gurugram', 'delhi-ncr', 'c++', 'hft', 'india'],
  },

  // ==========================================
  // 2. TOP INDIAN TECH UNICORNS & STARTUPS
  // ==========================================
  {
    companyName: 'Flipkart',
    companyWebsite: 'https://flipkart.com',
    industry: 'E-Commerce & Logistics',
    title: 'Software Development Engineer (SDE) Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹60,000 - ₹80,000 / month',
    benefits: 'Shopping discounts, transport allowance, health insurance, PPO opportunity',
    applicationUrl: 'https://flipkartcareers.com',
    deadline: new Date('2026-11-20'),
    description: 'Build distributed catalog search, high-volume checkout microservices, and warehouse automation for India’s premier e-commerce platform.',
    requirements: 'B.Tech/BE in CS/IT in India graduating in 2027. Proficiency in Java, Dropwizard, Kafka, and Redis.',
    tags: ['flipkart', 'internship', 'bengaluru', 'sde', 'java', 'ecommerce', 'india'],
  },
  {
    companyName: 'Swiggy',
    companyWebsite: 'https://swiggy.com',
    industry: 'FoodTech & Quick Commerce',
    title: 'Software Engineer Intern - Consumer Apps & Logistics',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Remote flexibility, Swiggy One perks, learning budget, PPO conversion',
    applicationUrl: 'https://careers.swiggy.com',
    deadline: new Date('2026-11-25'),
    description: 'Work on real-time delivery assignment algorithms, dynamic pricing engines, and Instamart quick-commerce checkout flows.',
    requirements: 'Comfortable with Golang, Java, or React Native. Strong analytical thinking and clean code design.',
    tags: ['swiggy', 'internship', 'bengaluru', 'remote', 'golang', 'quick-commerce', 'india'],
  },
  {
    companyName: 'Zomato',
    companyWebsite: 'https://zomato.com',
    industry: 'FoodTech & Hyperlocal',
    title: 'Software Development Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹60,000 - ₹85,000 / month',
    benefits: 'Free meals, fun campus environment, pre-placement offer opportunity',
    applicationUrl: 'https://zomato.com/careers',
    deadline: new Date('2026-11-18'),
    description: 'Build high-scale backend microservices and mobile application features for Zomato delivery and Blinkit quick commerce.',
    requirements: 'Undergraduate student in CS/IT in India. Experience in PHP/Go/Node.js, MySQL, and distributed caching.',
    tags: ['zomato', 'internship', 'gurugram', 'delhi-ncr', 'backend', 'golang', 'india'],
  },
  {
    companyName: 'Groww',
    companyWebsite: 'https://groww.in',
    industry: 'FinTech & Wealth Management',
    title: 'Software Engineering Intern - Stock Trading & Mutual Funds',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹60,000 - ₹90,000 / month',
    benefits: 'Free lunch and snacks, health insurance, direct impact on millions of Indian retail investors',
    applicationUrl: 'https://groww.in/careers',
    deadline: new Date('2026-11-22'),
    description: 'Build low-latency order placement pipelines connecting to Indian stock exchanges (NSE/BSE) and real-time market data streaming.',
    requirements: 'Solid grasp of Java, Spring Boot, microservices architecture, and WebSocket protocols.',
    tags: ['groww', 'internship', 'bengaluru', 'fintech', 'trading', 'java', 'india'],
  },
  {
    companyName: 'Meesho',
    companyWebsite: 'https://meesho.io',
    industry: 'Social E-Commerce',
    title: 'SDE Intern - Growth & Discovery Platform',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹65,000 - ₹85,000 / month',
    benefits: 'Work from anywhere in India, MacBook Pro, learning stipend, return offer path',
    applicationUrl: 'https://meesho.io/careers',
    deadline: new Date('2026-11-28'),
    description: 'Build recommendation engines, personalization algorithms, and supplier toolings for millions of tier-2 and tier-3 Indian shoppers.',
    requirements: 'Experience with Python, Java, or Golang. Knowledge of machine learning ranking models or backend API development.',
    tags: ['meesho', 'internship', 'bengaluru', 'remote', 'ecommerce', 'python', 'india'],
  },
  {
    companyName: 'Zerodha',
    companyWebsite: 'https://zerodha.com',
    industry: 'FinTech & Discount Brokerage',
    title: 'FOSS Engineering & Systems Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Open source ethos, calm work culture, healthcare coverage, book allowance',
    applicationUrl: 'https://zerodha.tech/careers',
    deadline: new Date('2026-12-01'),
    description: 'Build Kite trading platform tooling, open source financial libraries, and high-performance Postgres/Go backends with India’s largest stock broker.',
    requirements: 'Deep love for Free and Open Source Software (FOSS), Go, Python, Vue.js, or PostgreSQL. Active GitHub contributions.',
    tags: ['zerodha', 'internship', 'bengaluru', 'foss', 'golang', 'fintech', 'india'],
  },
  {
    companyName: 'InMobi',
    companyWebsite: 'https://inmobi.com',
    industry: 'AdTech & AI',
    title: 'Data Science & Software Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹70,000 / month',
    benefits: 'Mentorship from adtech pioneers, medical insurance, transport facilities',
    applicationUrl: 'https://inmobi.com/company/careers',
    deadline: new Date('2026-11-15'),
    description: 'Develop machine learning bidding engines processing billions of real-time ad auctions per second across mobile devices.',
    requirements: 'CS/Data Science background in India. Proficiency in Python, Spark, Java, and statistical modeling.',
    tags: ['inmobi', 'internship', 'bengaluru', 'adtech', 'data-science', 'ai', 'india'],
  },
  {
    companyName: 'MakeMyTrip',
    companyWebsite: 'https://makemytrip.com',
    industry: 'Travel & Hospitality Tech',
    title: 'Software Development Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹45,000 - ₹65,000 / month',
    benefits: 'Travel discounts, cafeteria access, mentorship, return offer opportunity',
    applicationUrl: 'https://careers.makemytrip.com',
    deadline: new Date('2026-11-18'),
    description: 'Build dynamic flight and hotel search aggregators, pricing prediction models, and mobile booking experiences.',
    requirements: 'B.Tech/BE in CS or IT in India. Good knowledge of Java, Spring Boot, React, or Node.js.',
    tags: ['makemytrip', 'internship', 'gurugram', 'delhi-ncr', 'travel', 'java', 'india'],
  },
  {
    companyName: 'Dream11',
    companyWebsite: 'https://dream11.com',
    industry: 'SportsTech & Gaming',
    title: 'Software Engineering Intern - High Throughput Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹75,000 - ₹1,00,000 / month',
    benefits: 'Sports stadium passes, gourmet food, health insurance, high PPO conversion',
    applicationUrl: 'https://careers.dream11.com',
    deadline: new Date('2026-11-20'),
    description: 'Build ultra-high-concurrency leaderboard engines handling 10M+ concurrent users during IPL match deadlines.',
    requirements: 'Strong CS fundamentals, experience with Java/Golang, Redis clustering, and distributed caching.',
    tags: ['dream11', 'internship', 'mumbai', 'sportstech', 'golang', 'distributed-systems', 'india'],
  },
  {
    companyName: 'Delhivery',
    companyWebsite: 'https://delhivery.com',
    industry: 'Logistics & Supply Chain',
    title: 'Data Science & SDE Intern - Route Optimization',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹45,000 - ₹65,000 / month',
    benefits: 'Health coverage, cafeteria, transport, PPO track',
    applicationUrl: 'https://delhivery.com/careers',
    deadline: new Date('2026-11-25'),
    description: 'Develop vehicle routing algorithms, automated sorting center robotics logic, and delivery SLA predictions across 18,000+ Indian pin codes.',
    requirements: 'Degree in CS/Operations Research/Math in India. Proficiency in Python, OR-Tools, and PostgreSQL.',
    tags: ['delhivery', 'internship', 'gurugram', 'delhi-ncr', 'logistics', 'python', 'india'],
  },
  {
    companyName: 'Slice',
    companyWebsite: 'https://sliceit.com',
    industry: 'FinTech & Digital Banking',
    title: 'Software Engineering Intern - Core Banking & Payments',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹60,000 - ₹85,000 / month',
    benefits: 'Fast-paced startup culture, health coverage, pre-placement offer pathway',
    applicationUrl: 'https://sliceit.com/careers',
    deadline: new Date('2026-11-20'),
    description: 'Build high-throughput core banking microservices, UPI transaction switches, and real-time fraud scoring engines.',
    requirements: 'Strong CS fundamentals, proficiency in Golang, Java, or Node.js, and experience with PostgreSQL.',
    tags: ['slice', 'internship', 'bengaluru', 'fintech', 'upi', 'golang', 'india'],
  },
  {
    companyName: 'Paytm',
    companyWebsite: 'https://paytm.com',
    industry: 'FinTech & Payments',
    title: 'Software Engineer Intern - Soundbox & Payments Switch',
    type: OpportunityType.INTERNSHIP,
    location: 'Noida, Uttar Pradesh, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹70,000 / month',
    benefits: 'Health insurance, transport assistance, high conversion rate to SDE-1',
    applicationUrl: 'https://paytm.com/careers/',
    deadline: new Date('2026-11-25'),
    description: 'Work on India’s largest merchant payment switch, UPI QR code processing backends, and Soundbox IoT firmware communication.',
    requirements: 'B.Tech/BE in CS/IT/ECE in India. Knowledge of Java, Spring Boot, Kafka, and Redis caching.',
    tags: ['paytm', 'internship', 'noida', 'delhi-ncr', 'fintech', 'payments', 'java', 'india'],
  },
  {
    companyName: 'Nykaa',
    companyWebsite: 'https://nykaa.com',
    industry: 'Beauty & Fashion E-Commerce',
    title: 'Software Development Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Product discounts, cafeteria, learning stipend, return offer path',
    applicationUrl: 'https://nykaa.com/careers',
    deadline: new Date('2026-11-22'),
    description: 'Build recommendation algorithms, personalized search rankers, and checkout systems for India’s premier beauty platform.',
    requirements: 'Undergraduate student in CS/IT in India. Good knowledge of Node.js, React, Java, or Python and MySQL.',
    tags: ['nykaa', 'internship', 'mumbai', 'ecommerce', 'nodejs', 'react', 'india'],
  },
  {
    companyName: 'Ola',
    companyWebsite: 'https://olacabs.com',
    industry: 'Mobility & EV Tech',
    title: 'Software Engineer Intern - Ride Dispatch & Map Algorithms',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹55,000 - ₹80,000 / month',
    benefits: 'Ola ride credits, free meals, high-growth startup environment',
    applicationUrl: 'https://olacabs.com/careers',
    deadline: new Date('2026-11-18'),
    description: 'Design geospatial routing engines, dynamic surge pricing models, and Ola Maps spatial query optimizers.',
    requirements: 'Solid grasp of Data Structures, Algorithms, Java/Go, and distributed key-value stores.',
    tags: ['ola', 'internship', 'bengaluru', 'mobility', 'maps', 'golang', 'india'],
  },
  {
    companyName: 'ShareChat',
    companyWebsite: 'https://sharechat.com',
    industry: 'Social Media & Short Video',
    title: 'Machine Learning & SDE Intern - Feed Ranking',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹70,000 - ₹95,000 / month',
    benefits: 'Work from anywhere in India, MacBook Pro, learning stipend, return offer pathway',
    applicationUrl: 'https://sharechat.com/careers',
    deadline: new Date('2026-11-28'),
    description: 'Build deep learning recommendation models for video feeds processing billions of daily impressions across 15+ Indian regional languages.',
    requirements: 'Strong proficiency in Python, PyTorch/TensorFlow, Golang, and deep recommendation networks.',
    tags: ['sharechat', 'internship', 'bengaluru', 'remote', 'machine-learning', 'nlp', 'india'],
  },
  {
    companyName: 'Lenskart',
    companyWebsite: 'https://lenskart.com',
    industry: 'Eyewear & AI Retail',
    title: 'Computer Vision & Software Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Faridabad, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹70,000 / month',
    benefits: 'Free eyewear allowances, shuttle transport from Delhi NCR, PPO conversion',
    applicationUrl: 'https://lenskart.com/careers',
    deadline: new Date('2026-11-30'),
    description: 'Develop 3D face mesh tracking, virtual try-on rendering pipelines, and automated optical factory sorting software.',
    requirements: 'B.Tech/M.Tech in CS/Data Science in India. Knowledge of OpenCV, PyTorch, C++, and React Native.',
    tags: ['lenskart', 'internship', 'faridabad', 'delhi-ncr', 'computer-vision', '3d', 'india'],
  },
  {
    companyName: 'Freshworks',
    companyWebsite: 'https://freshworks.com',
    industry: 'SaaS & Customer Support',
    title: 'Software Product Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Modern campus amenities, transport, return offer path, learning stipend',
    applicationUrl: 'https://freshworks.com/company/careers/',
    deadline: new Date('2026-11-20'),
    description: 'Build AI-powered ticketing workflows, omnichannel CRM tools, and cloud developer platforms serving 60,000+ businesses globally.',
    requirements: 'Pursuing CS/IT degree in India. Experience with Ruby on Rails, Java, Node.js, or React.',
    tags: ['freshworks', 'internship', 'chennai', 'saas', 'ruby', 'react', 'india'],
  },
  {
    companyName: 'Zoho',
    companyWebsite: 'https://zoho.com',
    industry: 'Cloud Software & Productivity',
    title: 'Software Developer Intern - Cloud Infrastructure',
    type: OpportunityType.INTERNSHIP,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹40,000 - ₹60,000 / month',
    benefits: 'Free accommodation, gourmet dining, calm culture, high full-time offer rate',
    applicationUrl: 'https://zoho.com/careers/',
    deadline: new Date('2026-12-01'),
    description: 'Work on proprietary database engines, email storage servers, and web office applications across Zoho’s self-managed data centers.',
    requirements: 'Enrolled in engineering in India. Strong C, C++, or Java fundamentals and understanding of OS and Networks.',
    tags: ['zoho', 'internship', 'chennai', 'cloud', 'c++', 'database', 'india'],
  },
  {
    companyName: 'Devfolio',
    companyWebsite: 'https://devfolio.co',
    industry: 'Developer Tools & Web3',
    title: 'Full Stack Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Work from anywhere in India, crypto/Web3 hackathon tickets, hardware allowance',
    applicationUrl: 'https://devfolio.co/careers',
    deadline: new Date('2026-11-25'),
    description: 'Build developer hackathon tooling, automated judging systems, and Web3 portfolio builders empowering 500,000+ builders.',
    requirements: 'Proficiency in TypeScript, Next.js, Node.js, GraphQL, and PostgreSQL.',
    tags: ['devfolio', 'internship', 'bengaluru', 'remote', 'typescript', 'nextjs', 'india'],
  },
  {
    companyName: 'BharatPe',
    companyWebsite: 'https://bharatpe.com',
    industry: 'FinTech & Merchant Lending',
    title: 'Backend Software Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹70,000 / month',
    benefits: 'Health insurance, meal coupons, fast PPO conversion',
    applicationUrl: 'https://bharatpe.com/careers',
    deadline: new Date('2026-11-18'),
    description: 'Build UPI settlement microservices, merchant loan underwriting engines, and POS transaction switches.',
    requirements: 'B.Tech student in CS/IT in India. Solid experience in Golang, Node.js, and MySQL/PostgreSQL.',
    tags: ['bharatpe', 'internship', 'gurugram', 'delhi-ncr', 'fintech', 'golang', 'india'],
  },

  // ==========================================
  // 3. RESEARCH LABS & SUPERCOMPUTING (INDIA)
  // ==========================================
  {
    companyName: 'IIT Madras',
    companyWebsite: 'https://iitm.ac.in',
    industry: 'Higher Education & Research',
    title: 'IIT Madras Summer Fellowship Programme 2027',
    type: OpportunityType.RESEARCH,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹15,000 / month stipend + Campus Hostel',
    benefits: 'Access to Robert Bosch Centre for Data Science and AI (RBCDSAI) and IITM Research Park',
    applicationUrl: 'https://sfp.iitm.ac.in/',
    deadline: new Date('2026-11-28'),
    description: '2-month summer research fellowship at IIT Madras working on Data Science, Deep Learning, Biomedical AI, and Quantum Computing.',
    requirements: 'Pre-final year undergraduate students (B.E./B.Tech) with exceptional academic performance in India.',
    tags: ['iit-madras', 'research', 'chennai', 'ai', 'data-science', 'fellowship', 'india'],
  },
  {
    companyName: 'IIT Delhi',
    companyWebsite: 'https://iitd.ac.in',
    industry: 'Higher Education & Research',
    title: 'IIT Delhi Summer Undergraduate Research Award (SURA) 2027',
    type: OpportunityType.RESEARCH,
    location: 'New Delhi, Delhi NCR, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹15,000 / month stipend + Hostel Stay',
    benefits: 'Certificate of excellence, full access to IIT Delhi supercomputing and nanotechnology facilities',
    applicationUrl: 'https://iitd.ac.in/research/summer-internship',
    deadline: new Date('2026-11-20'),
    description: 'Work with IIT Delhi faculty at the Yardi School of Artificial Intelligence and CSE Department on robotics, LLMs, and formal methods.',
    requirements: 'Enrolled in 2nd or 3rd year engineering at accredited Indian universities.',
    tags: ['iit-delhi', 'research', 'new-delhi', 'delhi-ncr', 'ai', 'robotics', 'india'],
  },
  {
    companyName: 'IIT Kanpur',
    companyWebsite: 'https://iitk.ac.in',
    industry: 'Higher Education & Research',
    title: 'IIT Kanpur SURGE Summer Research Fellowship 2027',
    type: OpportunityType.RESEARCH,
    location: 'Kanpur, Uttar Pradesh, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹12,500 - ₹20,000 / month stipend + Hostel',
    benefits: 'Publication opportunities, certificate signed by Dean of Academic Affairs, campus accommodation',
    applicationUrl: 'https://iitk.ac.in/surge/',
    deadline: new Date('2026-11-30'),
    description: 'Conduct fundamental research in Cyber Security (C3iHub), Autonomous Drones, and Theoretical Computer Science at IIT Kanpur.',
    requirements: 'B.Tech/BE students in India completing 2nd or 3rd year with CGPA >= 8.5/10.',
    tags: ['iit-kanpur', 'research', 'kanpur', 'cybersecurity', 'drones', 'india'],
  },
  {
    companyName: 'Tata Institute of Fundamental Research (TIFR)',
    companyWebsite: 'https://tifr.res.in',
    industry: 'Fundamental Science Research',
    title: 'TIFR Visiting Students Research Programme (VSRP) 2027',
    type: OpportunityType.RESEARCH,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹15,000 / month + Free Campus Accommodation & Travel',
    benefits: 'Direct access to TIFR Colaba sea-facing campus, supercomputer clusters, fast track for PhD admissions',
    applicationUrl: 'https://tifr.res.in/~vsrp/',
    deadline: new Date('2026-12-05'),
    description: 'Prestigious research programme at India’s premier fundamental research institute in Theoretical Computer Science, Quantum Information, and Astrophysics.',
    requirements: 'Pre-final year students of B.Tech, M.Sc, or Integrated Master’s in India in CS, Physics, or Math.',
    tags: ['tifr', 'research', 'mumbai', 'theoretical-cs', 'quantum', 'physics', 'india'],
  },
  {
    companyName: 'CDAC (Centre for Development of Advanced Computing)',
    companyWebsite: 'https://cdac.in',
    industry: 'National Supercomputing & Gov Tech',
    title: 'Supercomputing & AI Research Project Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Pune, Maharashtra, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹20,000 - ₹35,000 / month stipend',
    benefits: 'Hands-on access to PARAM supercomputers, Government of India certification',
    applicationUrl: 'https://cdac.in/index.aspx?id=internship',
    deadline: new Date('2026-11-25'),
    description: 'Build parallel MPI algorithms, GPU clusters, and High-Performance Computing (HPC) software on India’s National Supercomputing Mission infrastructure.',
    requirements: 'Enrolled in B.Tech/M.Tech in CS/IT in India. Strong C, C++, MPI, OpenMP, and Linux.',
    tags: ['cdac', 'hpc', 'supercomputing', 'pune', 'internship', 'mpi', 'india'],
  },
  {
    companyName: 'ISRO (Indian Space Research Organisation)',
    companyWebsite: 'https://isro.gov.in',
    industry: 'Aerospace & Satellite Tech',
    title: 'Student Project Intern - Satellite Image Processing & AI',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: 'Government Stipend + Access to ISRO Satellite Datasets',
    benefits: 'Official ISRO Project Completion Certificate, guidance from ISRO Space Scientists',
    applicationUrl: 'https://isro.gov.in/Internship.html',
    deadline: new Date('2026-12-01'),
    description: 'Work with ISRO Satellite Centre (URSC) on satellite telemetry processing, computer vision for earth observation, and space robotics simulations.',
    requirements: 'Citizen of India pursuing B.Tech/M.Tech in CS/ECE/Aerospace in an AICTE recognized university (Minimum 75% marks).',
    tags: ['isro', 'space', 'satellite', 'internship', 'bengaluru', 'computer-vision', 'india'],
  },

  // ==========================================
  // 4. MORE LEADING INDIAN TECH ENTERPRISES & UNICORNS
  // ==========================================
  {
    companyName: 'Infosys',
    companyWebsite: 'https://infosys.com',
    industry: 'IT & Cloud Consulting',
    title: 'Infosys InStep Flagship Software Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹40,000 - ₹60,000 / month + Global Campus Living',
    benefits: 'Ranked world #1 internship program, free stay at 350-acre Mysore/Bengaluru campus, executive mentoring',
    applicationUrl: 'https://infosys.com/instep.html',
    deadline: new Date('2026-11-30'),
    description: 'Work on cutting-edge Topaz AI, Infosys Cobalt Cloud, and open-source generative AI architectures.',
    requirements: 'Undergraduate or Graduate students in Computer Science / IT / Data Science in India with outstanding academic pedigree.',
    tags: ['infosys', 'instep', 'internship', 'bengaluru', 'ai', 'cloud', 'india'],
  },
  {
    companyName: 'Tata Consultancy Services (TCS)',
    companyWebsite: 'https://tcs.com',
    industry: 'IT & Advanced Research',
    title: 'TCS Research & Innovation Summer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Pune, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹35,000 - ₹50,000 / month',
    benefits: 'Co-authorship on research papers, patent filings, high PPO conversion to TCS Innovator',
    applicationUrl: 'https://tcs.com/careers/research-internships',
    deadline: new Date('2026-11-25'),
    description: 'Conduct applied scientific research in Quantum Computing, Cyber-Physical Systems, Genomics, and Foundation AI models.',
    requirements: 'B.Tech/M.Tech/PhD students in India. Strong math, Python, C++, and research methodology.',
    tags: ['tcs', 'research', 'internship', 'pune', 'quantum', 'ai', 'india'],
  },
  {
    companyName: 'Reliance Jio',
    companyWebsite: 'https://jio.com',
    industry: 'Telecom, 5G & Digital Services',
    title: 'Software Engineer Intern - 5G Core & Jio Platforms',
    type: OpportunityType.INTERNSHIP,
    location: 'Navi Mumbai, Maharashtra, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹45,000 - ₹65,000 / month',
    benefits: 'Subsidized corporate housing, Jio 5G campus testing lab access, return offer pathway',
    applicationUrl: 'https://careers.jio.com',
    deadline: new Date('2026-12-05'),
    description: 'Build cloud-native 5G core network functions, JioCinema ultra-low latency video streaming, and JioCloud storage backends.',
    requirements: 'B.Tech/BE in CS/ECE/IT in India. Solid understanding of Linux, Docker/K8s, C++, Golang, or Java.',
    tags: ['jio', 'reliance', 'internship', 'navi-mumbai', '5g', 'cloud', 'india'],
  },
  {
    companyName: 'Airtel',
    companyWebsite: 'https://airtel.in',
    industry: 'Telecom & Digital Platforms',
    title: 'Software Development Engineer Intern - Airtel X Labs',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹60,000 - ₹85,000 / month',
    benefits: 'Modern digital R&D campus in Cyber Hub, Airtel Thanks app perks, fast PPO track',
    applicationUrl: 'https://airtel.in/careers/x-labs',
    deadline: new Date('2026-11-20'),
    description: 'Work with Airtel X Labs developing AI fraud-prevention switches, Wynk music recommendations, and IoT smart metering backends.',
    requirements: 'Penultimate year engineering student in India. Strong Java, Spring Boot, Kafka, and distributed caches.',
    tags: ['airtel', 'x-labs', 'internship', 'gurugram', 'delhi-ncr', 'fintech', 'iot', 'india'],
  },
  {
    companyName: 'PhonePe',
    companyWebsite: 'https://phonepe.com',
    industry: 'FinTech & UPI Payments',
    title: 'Software Engineer Intern - High Concurrency Payment Switch',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹80,000 - ₹1,00,000 / month',
    benefits: 'Top-tier startup compensation, free gourmet meals, comprehensive health insurance, direct PPO route',
    applicationUrl: 'https://phonepe.com/careers',
    deadline: new Date('2026-11-18'),
    description: 'Architect and scale India’s largest UPI payments switch processing 7+ billion monthly transactions with 99.999% uptime.',
    requirements: 'B.Tech in CS/IT in India graduating in 2027. World-class mastery of Java, Concurrency, JVM internals, and Aerospike/HBase.',
    tags: ['phonepe', 'internship', 'bengaluru', 'fintech', 'upi', 'java', 'concurrency', 'india'],
  },
  {
    companyName: 'Razorpay',
    companyWebsite: 'https://razorpay.com',
    industry: 'FinTech & NeoBanking',
    title: 'Software Development Engineer Intern - RazorpayX & International Gateways',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹75,000 - ₹95,000 / month',
    benefits: 'MacBook Pro, wellness allowances, health coverage, high return offer rate',
    applicationUrl: 'https://razorpay.com/jobs',
    deadline: new Date('2026-11-22'),
    description: 'Build developer-first payment checkout SDKs, automated corporate banking microservices, and international payment routing.',
    requirements: 'Enrolled in Computer Science or related degree in India. Strong Golang, PHP, Node.js, and MySQL/PostgreSQL.',
    tags: ['razorpay', 'internship', 'bengaluru', 'fintech', 'golang', 'payments', 'india'],
  },
  {
    companyName: 'CRED',
    companyWebsite: 'https://cred.club',
    industry: 'FinTech & Premium Commerce',
    title: 'Backend Engineering Intern - Distributed Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹90,000 - ₹1,15,000 / month',
    benefits: 'Signature CRED workplace perks, high-end Apple hardware, gourmet cafeteria, PPO fast-track',
    applicationUrl: 'https://cred.club/careers',
    deadline: new Date('2026-11-15'),
    description: 'Design distributed event-driven microservices, credit card reward settlement pipelines, and real-time ledger accounting.',
    requirements: 'Outstanding grasp of Algorithms, Data Structures, Java / Kotlin / Golang, and high-throughput Kafka streaming.',
    tags: ['cred', 'internship', 'bengaluru', 'fintech', 'kotlin', 'kafka', 'distributed-systems', 'india'],
  },
  {
    companyName: 'Zepto',
    companyWebsite: 'https://zeptonow.com',
    industry: 'Quick Commerce & Logistics',
    title: 'Software Engineer Intern - Dark Store Automation & Routing',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹70,000 - ₹90,000 / month',
    benefits: 'Fastest growing unicorn environment, free daily meals, learning allowance, PPO opportunity',
    applicationUrl: 'https://zeptonow.com/careers',
    deadline: new Date('2026-11-25'),
    description: 'Build 10-minute order batching algorithms, automated micro-warehouse picking routes, and dynamic delivery partner allocation.',
    requirements: 'Proficiency in Golang, Python, or Java. Strong understanding of graphs, heuristics, and low-latency databases.',
    tags: ['zepto', 'internship', 'bengaluru', 'quick-commerce', 'golang', 'logistics', 'india'],
  },
  {
    companyName: 'Postman',
    companyWebsite: 'https://postman.com',
    industry: 'Developer Tools & API Platform',
    title: 'Software Engineering Intern - API Platform & Cloud Runtimes',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹80,000 - ₹1,00,000 / month',
    benefits: 'Remote flexibility across India, home office budget, health insurance, high PPO conversion',
    applicationUrl: 'https://postman.com/careers',
    deadline: new Date('2026-11-20'),
    description: 'Work on the core Postman API execution engine, collection runner cloud infrastructure, and collaborative API workspace tools.',
    requirements: 'Pursuing CS/IT degree in India. Deep knowledge of JavaScript, TypeScript, Node.js, Electron, and Web Protocols (HTTP/2, gRPC, WebSockets).',
    tags: ['postman', 'internship', 'bengaluru', 'remote', 'api', 'typescript', 'nodejs', 'india'],
  },
  {
    companyName: 'BrowserStack',
    companyWebsite: 'https://browserstack.com',
    industry: 'Cloud Infrastructure & Developer Testing',
    title: 'Software Engineering Intern - Distributed Cloud Testing',
    type: OpportunityType.INTERNSHIP,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹75,000 - ₹95,000 / month',
    benefits: 'Cutting-edge hyper-scale device cloud access, medical cover, return offer opportunity',
    applicationUrl: 'https://browserstack.com/careers',
    deadline: new Date('2026-11-28'),
    description: 'Build virtualization systems, real-device cloud automation, and browser rendering engines running millions of automated tests daily.',
    requirements: 'Strong proficiency in Ruby, Python, Golang, or C++. Familiarity with Linux internals, Docker, and hypervisors.',
    tags: ['browserstack', 'internship', 'mumbai', 'cloud', 'virtualization', 'golang', 'india'],
  },
  {
    companyName: 'Hasura',
    companyWebsite: 'https://hasura.io',
    industry: 'Developer Platforms & GraphQL',
    title: 'Engineering Intern - GraphQL Engine & Data Connectors',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹70,000 - ₹90,000 / month',
    benefits: 'Work from anywhere in India, open-source sponsorship, MacBook Pro',
    applicationUrl: 'https://hasura.io/careers/',
    deadline: new Date('2026-11-30'),
    description: 'Contribute to Hasura’s open-source GraphQL execution engine, query planners, and high-performance database connectors (Postgres, ClickHouse, Snowflake).',
    requirements: 'Strong functional programming background (Haskell, Rust, or Go) and relational database query optimization.',
    tags: ['hasura', 'internship', 'bengaluru', 'remote', 'graphql', 'rust', 'haskell', 'india'],
  },
  {
    companyName: 'Urban Company',
    companyWebsite: 'https://urbancompany.com',
    industry: 'Hyperlocal Services & Marketplace',
    title: 'Software Development Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹55,000 - ₹75,000 / month',
    benefits: 'Free in-home services allowance, gourmet meals, high PPO conversion',
    applicationUrl: 'https://urbancompany.com/careers',
    deadline: new Date('2026-11-18'),
    description: 'Build service partner matchmaking engines, real-time demand forecasting models, and consumer booking applications across 50+ cities.',
    requirements: 'Undergraduate student in CS/IT in India. Strong Node.js, React Native, Java, and MongoDB/Postgres.',
    tags: ['urban-company', 'internship', 'gurugram', 'delhi-ncr', 'marketplace', 'nodejs', 'india'],
  },
  {
    companyName: 'Ather Energy',
    companyWebsite: 'https://atherenergy.com',
    industry: 'EV & Smart Mobility',
    title: 'Embedded Firmware & IoT Software Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹40,000 - ₹60,000 / month',
    benefits: 'Ather EV testing rides, advanced electronics prototyping lab access, PPO path',
    applicationUrl: 'https://atherenergy.com/careers',
    deadline: new Date('2026-11-20'),
    description: 'Develop real-time dashboard OS, vehicle telemetry streaming, and Battery Management System (BMS) safety firmware.',
    requirements: 'B.Tech in CS/ECE/EEE in India. Strong C, C++, RTOS, CAN protocol, and Linux embedded systems.',
    tags: ['ather', 'ev', 'embedded', 'iot', 'internship', 'bengaluru', 'c++', 'india'],
  },
  {
    companyName: 'LeadSquared',
    companyWebsite: 'https://leadsquared.com',
    industry: 'SaaS & CRM',
    title: 'Software Engineering Intern - Cloud Platforms',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹45,000 - ₹65,000 / month',
    benefits: 'Health insurance, annual learning budget, high conversion rate to SDE-1',
    applicationUrl: 'https://leadsquared.com/careers',
    deadline: new Date('2026-11-22'),
    description: 'Build high-scale sales automation workflows, lead distribution microservices, and CRM database sharding solutions.',
    requirements: 'Pursuing engineering in India. Good knowledge of Java, Python, C#, or React and AWS basics.',
    tags: ['leadsquared', 'internship', 'bengaluru', 'saas', 'crm', 'java', 'india'],
  },
  {
    companyName: 'Chargebee',
    companyWebsite: 'https://chargebee.com',
    industry: 'FinTech & SaaS Billing',
    title: 'Product Engineering Intern - Subscription Billing',
    type: OpportunityType.INTERNSHIP,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'SaaS unicorn work culture, medical insurance, wellness budget, PPO track',
    applicationUrl: 'https://chargebee.com/careers',
    deadline: new Date('2026-11-25'),
    description: 'Work on global tax computation engines, recurring subscription lifecycle managers, and revenue recognition microservices.',
    requirements: 'B.Tech/BE in CS/IT in India. Solid proficiency in Java, Spring Boot, PostgreSQL, and REST API design.',
    tags: ['chargebee', 'internship', 'chennai', 'fintech', 'saas', 'java', 'india'],
  },
  {
    companyName: 'CleverTap',
    companyWebsite: 'https://clevertap.com',
    industry: 'AI & Customer Engagement',
    title: 'Software Development Engineer Intern - Big Data & Streaming',
    type: OpportunityType.INTERNSHIP,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹55,000 - ₹80,000 / month',
    benefits: 'Transport allowance, cafeteria, learning stipend, return offer path',
    applicationUrl: 'https://clevertap.com/careers',
    deadline: new Date('2026-11-28'),
    description: 'Develop custom in-memory database engines (TesseractDB) processing over 10 billion daily user engagement events.',
    requirements: 'Strong CS fundamentals, proficiency in C++, Java, or Go, and understanding of memory management and concurrency.',
    tags: ['clevertap', 'internship', 'mumbai', 'big-data', 'streaming', 'c++', 'india'],
  },
  {
    companyName: 'Icertis',
    companyWebsite: 'https://icertis.com',
    industry: 'Enterprise SaaS & LegalTech AI',
    title: 'Software Development Engineer Intern - Contract Intelligence AI',
    type: OpportunityType.INTERNSHIP,
    location: 'Pune, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹70,000 / month',
    benefits: 'Modern campus at Magarpatta City, comprehensive insurance, fast PPO conversion',
    applicationUrl: 'https://icertis.com/careers',
    deadline: new Date('2026-11-20'),
    description: 'Build enterprise contract management workflows and LLM reasoning pipelines summarizing complex legal documents.',
    requirements: 'Pursuing Bachelor’s or Master’s in Computer Science in India. Strong C#, .NET Core, Python, or Angular.',
    tags: ['icertis', 'internship', 'pune', 'saas', 'dotnet', 'ai', 'india'],
  },
  {
    companyName: 'MapmyIndia',
    companyWebsite: 'https://mapmyindia.com',
    industry: 'Geospatial Tech & Navigation',
    title: 'Geospatial AI & Software Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'New Delhi, Delhi NCR, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹40,000 - ₹60,000 / month',
    benefits: 'Access to high-definition 3D map datasets, drone survey analytics, PPO opportunity',
    applicationUrl: 'https://mapmyindia.com/careers',
    deadline: new Date('2026-11-30'),
    description: 'Build GIS spatial indexing algorithms, automated road defect detection models, and 3D digital twin visualization engines.',
    requirements: 'B.Tech in CS/IT/Geoinformatics in India. Experience in Python, C++, PostGIS, and Computer Vision.',
    tags: ['mapmyindia', 'internship', 'new-delhi', 'delhi-ncr', 'geospatial', 'maps', 'india'],
  },
  {
    companyName: 'Gupshup',
    companyWebsite: 'https://gupshup.io',
    industry: 'Conversational AI & Messaging',
    title: 'Software Engineer Intern - Conversational AI & WhatsApp Bot Engine',
    type: OpportunityType.INTERNSHIP,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹45,000 - ₹65,000 / month',
    benefits: 'Health insurance, meal passes, return offer pathway',
    applicationUrl: 'https://gupshup.io/careers',
    deadline: new Date('2026-11-22'),
    description: 'Work on conversational commerce bots, multi-channel messaging switches handling 10B+ monthly messages, and Generative AI agents.',
    requirements: 'Undergraduate student in CS/IT in India. Good knowledge of Java, Node.js, Python, and cloud APIs.',
    tags: ['gupshup', 'internship', 'mumbai', 'conversational-ai', 'whatsapp', 'nodejs', 'india'],
  },
  {
    companyName: 'Fractal Analytics',
    companyWebsite: 'https://fractal.ai',
    industry: 'AI, Analytics & Consulting',
    title: 'AI & Data Science Intern (Applied AI Labs)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹45,000 - ₹70,000 / month',
    benefits: 'Fractal Analytics Academy training, comprehensive healthcare, PPO opportunity',
    applicationUrl: 'https://fractal.ai/careers/',
    deadline: new Date('2026-11-28'),
    description: 'Build computer vision models for retail shelf monitoring, conversational analytics, and automated machine learning pipelines.',
    requirements: 'Enrolled in engineering or data science degree in India. Proficiency in Python, Scikit-learn, PyTorch, and SQL.',
    tags: ['fractal', 'ai', 'data-science', 'internship', 'bengaluru', 'python', 'india'],
  },
  {
    companyName: 'Darwinbox',
    companyWebsite: 'https://darwinbox.com',
    industry: 'Enterprise HR Tech & Cloud',
    title: 'Software Engineering Intern - Core HRMS & Cloud Microservices',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹45,000 - ₹65,000 / month',
    benefits: 'Fastest growing HR tech unicorn, modern campus, pre-placement offer pathway',
    applicationUrl: 'https://darwinbox.com/careers',
    deadline: new Date('2026-11-20'),
    description: 'Build enterprise HR architecture, attendance facial recognition modules, and payroll computation microservices serving 1,000+ enterprises.',
    requirements: 'B.Tech/BE in CS/IT in India. Strong foundations in Node.js, Golang, PHP, or React and relational databases.',
    tags: ['darwinbox', 'internship', 'hyderabad', 'saas', 'hrms', 'nodejs', 'india'],
  },
  {
    companyName: 'Keka',
    companyWebsite: 'https://keka.com',
    industry: 'HR Tech & Payroll Cloud',
    title: 'Software Development Engineer Intern - Payroll Engine & Cloud Architecture',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹40,000 - ₹60,000 / month',
    benefits: 'Calm and collaborative culture, free meals, health insurance, high PPO conversion',
    applicationUrl: 'https://keka.com/careers',
    deadline: new Date('2026-11-25'),
    description: 'Develop high-performance payroll calculation engines, employee tax compliance calculators, and modern SaaS web interfaces.',
    requirements: 'Pursuing Computer Science or related degree in India. Experience with C# / .NET, React, and SQL Server.',
    tags: ['keka', 'internship', 'hyderabad', 'hrms', 'saas', 'dotnet', 'react', 'india'],
  },
];

