import { prisma } from '../lib/db';
import { OpportunityType, RemoteType } from '../lib/generated/prisma/enums';
import { EnrichmentEngine } from '../lib/ai/enrichment-engine';

interface IndianOppRecord {
  companyName: string;
  companyWebsite: string;
  industry: string;
  title: string;
  type: OpportunityType;
  location: string;
  remoteType: RemoteType;
  salaryRange: string;
  benefits?: string;
  applicationUrl: string;
  deadline: Date;
  description: string;
  requirements: string;
  tags: string[];
}

export const MASSIVE_INDIAN_CATALOG: IndianOppRecord[] = [
  // =========================================================================
  // 1. TIER-1 TECH & PRODUCT MNCs (INDIAN DEVELOPMENT CENTERS)
  // =========================================================================
  {
    companyName: 'Google',
    companyWebsite: 'https://careers.google.com',
    industry: 'Technology & Cloud',
    title: 'Software Engineering Intern, Summer 2027',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,25,000 - ₹1,50,000 / month',
    benefits: 'High PPO conversion, gourmet meals, shuttle service, health insurance',
    applicationUrl: 'https://careers.google.com/jobs/results/software-engineering-intern-bangalore/',
    deadline: new Date('2026-12-15'),
    description: 'Work on core Google products including Google Search, Android, Google Pay India, and Google Cloud platform services.',
    requirements: 'Enrolled in Bachelor or Master CS/IT degree in India graduating in 2027 or 2028. Strong Data Structures, Algorithms, C++, Java, or Python.',
    tags: ['google', 'internship', 'bengaluru', 'swe', 'algorithms', 'india'],
  },
  {
    companyName: 'Google',
    companyWebsite: 'https://careers.google.com',
    industry: 'Technology & Cloud',
    title: 'STEP Internship 2027 (Student Training in Engineering Program)',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹85,000 - ₹1,15,000 / month',
    benefits: 'Relocation assistance, mentorship, return offer pathway, learning stipends',
    applicationUrl: 'https://buildyourfuture.withgoogle.com/step',
    deadline: new Date('2026-11-30'),
    description: 'Developmental software internship for 1st & 2nd year undergraduate students across India with direct mentorship from Google Engineers.',
    requirements: 'Currently enrolled in an undergraduate degree in Computer Science or related field in India; graduating in 2028 or 2029.',
    tags: ['google', 'step', 'internship', 'hyderabad', 'first-year', 'second-year', 'india'],
  },
  {
    companyName: 'Google',
    companyWebsite: 'https://careers.google.com',
    industry: 'Technology & Cloud',
    title: 'Cloud Technical Solutions Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,00,000 / month',
    benefits: 'Google Cloud certification vouchers, mentorship, housing assistance',
    applicationUrl: 'https://careers.google.com/jobs/results/cloud-technical-solutions-intern',
    deadline: new Date('2026-12-05'),
    description: 'Diagnose and resolve complex architectural challenges on Google Cloud Platform (GCP) including BigQuery, Kubernetes Engine, and IAM.',
    requirements: 'Pursuing Bachelor’s or Master’s in Computer Science/IT/ECE in India. Strong networking, Linux, and scripting in Python or Go.',
    tags: ['google', 'gcp', 'cloud', 'internship', 'bengaluru', 'linux', 'india'],
  },
  {
    companyName: 'Microsoft',
    companyWebsite: 'https://careers.microsoft.com',
    industry: 'Technology & Cloud',
    title: 'Software Engineering Intern - Microsoft India Development Center (IDC)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,25,000 / month',
    benefits: 'Housing allowance, wellness reimbursement, Microsoft Surface hardware, medical coverage',
    applicationUrl: 'https://careers.microsoft.com/us/en/job/1689234/software-engineering-intern',
    deadline: new Date('2026-11-20'),
    description: 'Build enterprise cloud architectures, generative AI copilots, and distributed systems powering Microsoft Azure and Office 365.',
    requirements: 'Pursuing B.Tech/M.Tech/Dual Degree in CS/IT or relevant engineering discipline in India. Strong C++, C#, Java, or Python foundations.',
    tags: ['microsoft', 'idc', 'internship', 'bengaluru', 'azure', 'copilot', 'india'],
  },
  {
    companyName: 'Microsoft',
    companyWebsite: 'https://careers.microsoft.com',
    industry: 'Technology & Cloud',
    title: 'Software Engineering Intern - Cloud & AI Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,25,000 / month',
    benefits: 'Cab transport, fitness perks, relocation allowance, high PPO conversion',
    applicationUrl: 'https://careers.microsoft.com/us/en/job/1689235/software-engineering-intern-hyderabad',
    deadline: new Date('2026-11-25'),
    description: 'Work on hyper-scale infrastructure, security services, and developer tooling at Microsoft IDC Hyderabad campus.',
    requirements: 'B.Tech / M.Tech students graduating in 2027 or 2028. Strong algorithm problem-solving skills.',
    tags: ['microsoft', 'internship', 'hyderabad', 'cloud', 'ai', 'india'],
  },
  {
    companyName: 'Microsoft',
    companyWebsite: 'https://careers.microsoft.com',
    industry: 'Technology & Cloud',
    title: 'Data & Applied Sciences Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Noida, Uttar Pradesh, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,30,000 / month',
    benefits: 'Relocation assistance, Azure OpenAI compute quota, high PPO conversion',
    applicationUrl: 'https://careers.microsoft.com/us/en/job/1689240/data-scientist-intern-noida',
    deadline: new Date('2026-12-01'),
    description: 'Build machine learning models, search ranking pipelines for Bing, and LLM fine-tuning pipelines for Copilot services.',
    requirements: 'Master or Bachelor student in CS, Data Science, or Math in India. Proficiency in Python, PyTorch, and statistics.',
    tags: ['microsoft', 'data-science', 'internship', 'noida', 'delhi-ncr', 'ai', 'india'],
  },
  {
    companyName: 'Amazon',
    companyWebsite: 'https://amazon.jobs',
    industry: 'E-Commerce & Cloud',
    title: 'Software Development Engineer (SDE) Intern - Summer 2027',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,10,000 / month',
    benefits: 'Housing allowance, round-trip travel reimbursement, Amazon Prime, high return offer rate',
    applicationUrl: 'https://amazon.jobs/en/jobs/2589012/software-development-engineer-intern',
    deadline: new Date('2026-11-30'),
    description: 'Design and build high-throughput backend services powering AWS cloud, Amazon.in retail platform, and Alexa Voice AI.',
    requirements: 'Enrolled in an Indian university degree in Computer Science; graduation in 2027 or 2028. Strong Java, C++, or Go.',
    tags: ['amazon', 'sde', 'internship', 'bengaluru', 'aws', 'backend', 'india'],
  },
  {
    companyName: 'Amazon',
    companyWebsite: 'https://amazon.jobs',
    industry: 'E-Commerce & Cloud',
    title: 'Software Development Engineer (SDE) Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,10,000 / month',
    benefits: 'Housing stipend, meal coupons, relocation assistance, PPO track',
    applicationUrl: 'https://amazon.jobs/en/jobs/2589013/software-development-engineer-intern-hyderabad',
    deadline: new Date('2026-12-05'),
    description: 'Build automated supply chain optimization models, logistics engines, and payment gateways for global and Indian customers.',
    requirements: 'B.Tech/BE/M.Tech students in India graduating 2027/2028. Solid grasp of OOP, OS, and DBMS concepts.',
    tags: ['amazon', 'sde', 'internship', 'hyderabad', 'java', 'india'],
  },
  {
    companyName: 'Amazon',
    companyWebsite: 'https://amazon.jobs',
    industry: 'E-Commerce & Cloud',
    title: 'Data Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹95,000 / month',
    benefits: 'Transport allowance, meal vouchers, AWS certifications sponsorship',
    applicationUrl: 'https://amazon.jobs/en/jobs/data-engineer-intern-chennai',
    deadline: new Date('2026-11-28'),
    description: 'Design and scale big data pipelines, Redshift data warehouses, and Spark ETL streaming pipelines processing petabytes of consumer analytics.',
    requirements: 'Pursuing CS/IT/Data Engineering in India. Strong SQL, Python, Spark, and data modeling concepts.',
    tags: ['amazon', 'data-engineering', 'internship', 'chennai', 'sql', 'spark', 'india'],
  },
  {
    companyName: 'Apple',
    companyWebsite: 'https://apple.com/careers',
    industry: 'Consumer Tech & Hardware',
    title: 'Software Engineering Intern - Maps & Core OS',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,20,000 / month',
    benefits: 'Apple product discounts, relocation assistance, health coverage, executive mentorship',
    applicationUrl: 'https://jobs.apple.com/en-in/details/200542312/software-engineering-intern',
    deadline: new Date('2026-11-28'),
    description: 'Work with the Apple Maps and Core OS engineering teams in Hyderabad on geospatial algorithms, routing graph pipelines, and iOS frameworks.',
    requirements: 'Enrolled in Computer Science or related degree in India. Strong C++, Swift, Python, and data structures proficiency.',
    tags: ['apple', 'internship', 'hyderabad', 'maps', 'c++', 'swift', 'india'],
  },
  {
    companyName: 'Apple',
    companyWebsite: 'https://apple.com/careers',
    industry: 'Consumer Tech & Hardware',
    title: 'Hardware & Silicon Validation Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,15,000 / month',
    benefits: 'Relocation housing, lab equipment access, mentorship from Apple Silicon architects',
    applicationUrl: 'https://jobs.apple.com/en-in/details/200542315/hardware-intern-bangalore',
    deadline: new Date('2026-12-05'),
    description: 'Validate next-generation Apple Silicon SoC architectures, perform power/performance simulations, and build automated verification testbenches.',
    requirements: 'Pursuing B.Tech/M.Tech in ECE/EE/VLSI in India. Knowledge of Verilog, SystemVerilog, Python scripting, and computer architecture.',
    tags: ['apple', 'silicon', 'vlsi', 'internship', 'bengaluru', 'hardware', 'india'],
  },
  {
    companyName: 'Meta',
    companyWebsite: 'https://metacareers.com',
    industry: 'Social Tech & AI',
    title: 'Software Engineering Intern - Infrastructure & Network Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,50,000 / month',
    benefits: 'Meta Quest device, housing stipend, free gourmet meals, return offer pathway',
    applicationUrl: 'https://metacareers.com/jobs/software-engineering-intern-india',
    deadline: new Date('2026-11-30'),
    description: 'Build hyper-scale network infrastructure, content delivery caching, and datacenter telemetry supporting WhatsApp, Instagram, and Facebook.',
    requirements: 'Pursuing Computer Science or related degree in India. Strong C++, Python, Linux networking, and distributed systems.',
    tags: ['meta', 'internship', 'bengaluru', 'infrastructure', 'c++', 'networking', 'india'],
  },
  {
    companyName: 'Adobe',
    companyWebsite: 'https://adobe.com/careers',
    industry: 'Creative & Digital Software',
    title: 'Software Development Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Noida, Uttar Pradesh, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,00,000 / month',
    benefits: 'Creative Cloud subscription, wellness reimbursement, shuttle transport, PPO conversion',
    applicationUrl: 'https://adobe.wd5.myworkdayjobs.com/adobe-careers/job/Noida/SDE-Intern',
    deadline: new Date('2026-11-25'),
    description: 'Develop features for Adobe Creative Cloud, Acrobat Document Cloud, and Adobe Firefly generative AI tools.',
    requirements: 'B.Tech/Dual Degree students graduating 2027. Strong C++, Java, or Web technologies (WebAssembly, WebGL).',
    tags: ['adobe', 'internship', 'noida', 'delhi-ncr', 'c++', 'firefly', 'india'],
  },
  {
    companyName: 'Nvidia',
    companyWebsite: 'https://nvidia.com/careers',
    industry: 'AI, GPUs & Hardware',
    title: 'System Software Engineering Intern - GPU Computing & CUDA',
    type: OpportunityType.INTERNSHIP,
    location: 'Pune, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹95,000 - ₹1,20,000 / month',
    benefits: 'Nvidia stock purchase plan eligibility, high-end GPU workstations, mentorship',
    applicationUrl: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/India-Pune/Software-Intern',
    deadline: new Date('2026-11-18'),
    description: 'Optimize CUDA compilers, GPU device drivers, and AI acceleration runtimes (TensorRT) for LLM training and inference.',
    requirements: 'Pursuing Bachelor’s or Master’s in CS/ECE in India. Deep knowledge of C, C++, Computer Architecture, and Operating Systems.',
    tags: ['nvidia', 'internship', 'pune', 'cuda', 'c++', 'gpu', 'ai', 'india'],
  },
  {
    companyName: 'Nvidia',
    companyWebsite: 'https://nvidia.com/careers',
    industry: 'AI, GPUs & Hardware',
    title: 'Deep Learning Software Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,10,000 / month',
    benefits: 'DGX Cloud access, cutting-edge AI research environment, return offer pathway',
    applicationUrl: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/India-Bengaluru/Deep-Learning-Intern',
    deadline: new Date('2026-12-05'),
    description: 'Work on transformer architectures, NeMo framework, and AI model quantization for enterprise generative AI deployments.',
    requirements: 'Strong background in Deep Learning, PyTorch, CUDA, and high-performance Python/C++.',
    tags: ['nvidia', 'internship', 'bengaluru', 'deep-learning', 'pytorch', 'india'],
  },
  {
    companyName: 'Qualcomm',
    companyWebsite: 'https://qualcomm.com/careers',
    industry: 'Semiconductors & Wireless',
    title: 'Software Engineer Intern - Snapdragon AI & Modem Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹85,000 - ₹1,05,000 / month',
    benefits: 'Relocation allowance, comprehensive health cover, lab equipment access',
    applicationUrl: 'https://qualcomm.wd5.myworkdayjobs.com/External/job/Hyderabad-IND/Engineer-Intern',
    deadline: new Date('2026-11-30'),
    description: 'Design low-level software, 5G protocol stacks, and NPU firmware for Snapdragon mobile and automotive platforms.',
    requirements: 'B.Tech/M.Tech in CS/ECE/EEE in India. Proficiency in Embedded C, C++, Linux kernel, and Microcontrollers.',
    tags: ['qualcomm', 'internship', 'hyderabad', 'embedded', 'snapdragon', '5g', 'india'],
  },
  {
    companyName: 'Cisco',
    companyWebsite: 'https://cisco.com/careers',
    industry: 'Networking & Cybersecurity',
    title: 'Software Engineer Intern - Cloud & Network Security',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹90,000 - ₹1,10,000 / month',
    benefits: 'Fitness reimbursement, Cisco certifications coverage, hybrid flexibility',
    applicationUrl: 'https://jobs.cisco.com/jobs/SearchJobs/India-Software-Engineer-Intern',
    deadline: new Date('2026-12-10'),
    description: 'Build enterprise networking software, secure SD-WAN controllers, and cloud threat intelligence pipelines.',
    requirements: 'Enrolled in Computer Science/IT/ECE in India. Solid knowledge of TCP/IP, Computer Networks, Linux, and Python/Go/C++.',
    tags: ['cisco', 'internship', 'bengaluru', 'networking', 'security', 'python', 'india'],
  },
  {
    companyName: 'Intel',
    companyWebsite: 'https://intel.com/careers',
    industry: 'Semiconductors & Computing',
    title: 'Graduate Technical Intern - Silicon Architecture & Software',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹80,000 - ₹1,00,000 / month',
    benefits: 'Silicon design tools training, medical benefits, transport facilities',
    applicationUrl: 'https://jobs.intel.com/en/search-jobs/India/Intern',
    deadline: new Date('2026-11-20'),
    description: 'Validate hardware IP blocks, develop system firmware/BIOS, and write software benchmarks for Intel Xeon and Core processors.',
    requirements: 'Pursuing B.Tech/M.Tech in CS/ECE/VLSI in India. Knowledge of Verilog/VHDL, Python scripting, or C/C++.',
    tags: ['intel', 'internship', 'bengaluru', 'vlsi', 'silicon', 'c++', 'india'],
  },
  {
    companyName: 'AMD',
    companyWebsite: 'https://amd.com/careers',
    industry: 'Semiconductors & AI',
    title: 'Software Development Intern - ROCm & AI Software Ecosystem',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹85,000 - ₹1,05,000 / month',
    benefits: 'AMD hardware discounts, flexible work hours, learning allowance',
    applicationUrl: 'https://careers.amd.com/careers-home/jobs?keywords=intern&location=India',
    deadline: new Date('2026-11-28'),
    description: 'Contribute to AMD’s open-source ROCm GPU computing platform, PyTorch optimizations, and server AI accelerators.',
    requirements: 'Enrolled in Computer Science or Electrical Engineering in India. Strong C++, Python, and Linux systems background.',
    tags: ['amd', 'internship', 'hyderabad', 'rocm', 'gpu', 'ai', 'india'],
  },
  {
    companyName: 'Oracle',
    companyWebsite: 'https://oracle.com/careers',
    industry: 'Database & Cloud Infrastructure',
    title: 'Software Developer Intern - Oracle Cloud Infrastructure (OCI)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹85,000 - ₹1,10,000 / month',
    benefits: 'Oracle certification courses, health coverage, high return offer conversion',
    applicationUrl: 'https://oracle.com/corporate/careers/students-graduates/',
    deadline: new Date('2026-11-25'),
    description: 'Build core cloud control plane services, distributed block storage engines, and virtualization layers for OCI.',
    requirements: 'Pursuing B.Tech/BE/M.Tech in CS in India. Strong foundations in Java, C++, Go, and distributed systems.',
    tags: ['oracle', 'oci', 'cloud', 'internship', 'bengaluru', 'java', 'india'],
  },
  {
    companyName: 'SAP',
    companyWebsite: 'https://sap.com/careers',
    industry: 'Enterprise Software & ERP',
    title: 'Developer Intern - SAP Labs India',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Hostel and meal support, global innovation summits, PPO conversion',
    applicationUrl: 'https://jobs.sap.com/search/?q=Intern&locationsearch=India',
    deadline: new Date('2026-11-30'),
    description: 'Develop cloud-native microservices for SAP Business Technology Platform, in-memory HANA database engines, and enterprise AI bots.',
    requirements: 'Enrolled in CS/IT in India graduating in 2027. Experience with Java, Node.js, Spring Boot, or Python.',
    tags: ['sap', 'internship', 'bengaluru', 'hana', 'cloud', 'enterprise', 'india'],
  },
  {
    companyName: 'ServiceNow',
    companyWebsite: 'https://servicenow.com/careers',
    industry: 'Cloud Workflow Automation',
    title: 'Software Engineering Intern - Now Platform',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹90,000 - ₹1,15,000 / month',
    benefits: 'Relocation stipend, high return offer rate, wellness days',
    applicationUrl: 'https://careers.servicenow.com/jobs?keywords=Intern&location=India',
    deadline: new Date('2026-12-05'),
    description: 'Design and optimize scalable cloud workflows, generative AI agent builders, and enterprise security platforms.',
    requirements: 'Undergraduate student in CS/IT in India graduating in 2027. Proficiency in Java, JavaScript/TypeScript, and relational DBs.',
    tags: ['servicenow', 'internship', 'hyderabad', 'java', 'automation', 'cloud', 'india'],
  },
  {
    companyName: 'Snowflake',
    companyWebsite: 'https://snowflake.com/careers',
    industry: 'Cloud Data Platform',
    title: 'Software Engineer Intern - Core Data Engine',
    type: OpportunityType.INTERNSHIP,
    location: 'Pune, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,20,000 - ₹1,50,000 / month',
    benefits: 'Competitive housing allowance, lunch and dinner, top-tier compensation',
    applicationUrl: 'https://snowflake.com/en/company/careers/',
    deadline: new Date('2026-11-20'),
    description: 'Work on Snowflake’s distributed SQL query compiler, execution engine, metadata transactions, and columnar storage format.',
    requirements: 'Enrolled in Computer Science/Engineering in India. Strong C++, Java, FoundationDB, or distributed query processing concepts.',
    tags: ['snowflake', 'internship', 'pune', 'database', 'c++', 'sql', 'india'],
  },
  {
    companyName: 'Databricks',
    companyWebsite: 'https://databricks.com/careers',
    industry: 'Data & AI Lakehouse',
    title: 'Software Engineering Intern - Apache Spark & ML Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,25,000 - ₹1,60,000 / month',
    benefits: 'Home office budget, high PPO conversion rate, compute access',
    applicationUrl: 'https://databricks.com/company/careers/open-positions?location=India',
    deadline: new Date('2026-11-22'),
    description: 'Build open-source distributed compute infrastructure, MLflow tracking platforms, and Delta Lake storage optimization layers.',
    requirements: 'Top-tier problem solving, Scala, Java, or C++, and knowledge of distributed computing algorithms.',
    tags: ['databricks', 'internship', 'bengaluru', 'spark', 'scala', 'ai', 'india'],
  },
  {
    companyName: 'Synopsys',
    companyWebsite: 'https://synopsys.com/careers',
    industry: 'Electronic Design Automation (EDA)',
    title: 'R&D Engineering Intern - IC Compiler & Verification',
    type: OpportunityType.INTERNSHIP,
    location: 'Noida, Uttar Pradesh, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹60,000 - ₹80,000 / month',
    benefits: 'Access to industry-standard EDA tools, transport, medical insurance',
    applicationUrl: 'https://synopsys.com/careers/university-relations.html',
    deadline: new Date('2026-11-30'),
    description: 'Develop graph optimization algorithms, logic synthesis engines, and formal verification software for complex sub-3nm chip designs.',
    requirements: 'B.Tech/M.Tech in CS/EE in India. Exceptional C++, Data Structures, Graph Theory, and Algorithm Optimization.',
    tags: ['synopsys', 'internship', 'noida', 'delhi-ncr', 'eda', 'c++', 'algorithms', 'india'],
  },
  {
    companyName: 'Cadence Design Systems',
    companyWebsite: 'https://cadence.com/careers',
    industry: 'Electronic Design Automation (EDA)',
    title: 'Software Engineering Intern - Logic Simulation & Emulation',
    type: OpportunityType.INTERNSHIP,
    location: 'Noida, Uttar Pradesh, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹65,000 - ₹85,000 / month',
    benefits: 'Hardware emulator access, wellness allowance, return offer pathway',
    applicationUrl: 'https://cadence.wd1.myworkdayjobs.com/External_Careers/job/Noida-India/Software-Intern',
    deadline: new Date('2026-11-25'),
    description: 'Build ultra-fast hardware emulation runtimes, waveform debugging software, and parallel simulation compilers.',
    requirements: 'Pursuing CS/ECE/VLSI in India. Strong C++, Multithreading, and Computer Architecture fundamentals.',
    tags: ['cadence', 'internship', 'noida', 'delhi-ncr', 'c++', 'simulation', 'india'],
  },
  {
    companyName: 'Texas Instruments',
    companyWebsite: 'https://ti.com/careers',
    industry: 'Semiconductors & Analog Tech',
    title: 'Analog & Embedded Software Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹75,000 - ₹95,000 / month',
    benefits: 'Subsidized housing, gym facilities, direct project ownership',
    applicationUrl: 'https://careers.ti.com/search-jobs/?location=India',
    deadline: new Date('2026-11-18'),
    description: 'Develop real-time DSP control algorithms, microcontroller SDKs, and automated semiconductor testing platforms.',
    requirements: 'B.Tech/M.Tech in ECE/EEE/CS in India. Strong C, Embedded Systems, Microcontrollers, and Signals & Systems.',
    tags: ['texas-instruments', 'internship', 'bengaluru', 'embedded', 'c', 'semiconductors', 'india'],
  },
  {
    companyName: 'Arm',
    companyWebsite: 'https://arm.com/careers',
    industry: 'Semiconductor IP & Architecture',
    title: 'Graduate Engineering Intern - CPU Architecture & Compilers',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹80,000 - ₹1,05,000 / month',
    benefits: 'Arm IP architecture training, comprehensive healthcare, return offer track',
    applicationUrl: 'https://arm.com/company/careers/early-careers',
    deadline: new Date('2026-11-22'),
    description: 'Model future Arm Cortex processor microarchitectures, optimize LLVM compiler backend passes, and simulate pipeline performance.',
    requirements: 'B.Tech/M.Tech in CS/EE in India. Knowledge of Assembly, C++, Computer Architecture, and Compilers.',
    tags: ['arm', 'internship', 'bengaluru', 'cpu', 'compilers', 'llvm', 'india'],
  },
  {
    companyName: 'Bosch',
    companyWebsite: 'https://bosch.in/careers',
    industry: 'Automotive & IoT',
    title: 'Embedded Software Intern - ADAS & Connected Mobility',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹40,000 - ₹60,000 / month',
    benefits: 'Transport, cafeteria, AUTOSAR training, return offer pathway',
    applicationUrl: 'https://bosch.in/careers/students-and-graduates/',
    deadline: new Date('2026-11-30'),
    description: 'Develop AUTOSAR firmware, radar/camera sensor fusion algorithms, and vehicle telemetry microcontrollers for electric & autonomous cars.',
    requirements: 'Enrolled in ECE/EEE/CS in India. Embedded C, Microcontrollers (ARM Cortex-M), CAN protocol, and Linux.',
    tags: ['bosch', 'internship', 'bengaluru', 'automotive', 'embedded', 'iot', 'india'],
  },
  {
    companyName: 'Mercedes-Benz R&D India',
    companyWebsite: 'https://mbrdi.co.in',
    industry: 'Automotive Software & EV',
    title: 'Software Engineering Intern - MB.OS Infotainment & Telemetry',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹45,000 - ₹65,000 / month',
    benefits: 'Modern R&D campus, transportation, mentorship from German automotive leaders',
    applicationUrl: 'https://mbrdi.co.in/careers/',
    deadline: new Date('2026-11-25'),
    description: 'Build cloud-connected infotainment apps, over-the-air (OTA) update engines, and battery management software for luxury electric vehicles.',
    requirements: 'B.Tech in CS/ECE/IT in India. Experience with C++, Android Automotive (AAOS), Qt/QML, or Python.',
    tags: ['mercedes-benz', 'internship', 'bengaluru', 'automotive', 'c++', 'ev', 'india'],
  },

  // =========================================================================
  // 2. QUANTITATIVE TRADING, FINTECH & INVESTMENT BANKS IN INDIA
  // =========================================================================
  {
    companyName: 'Graviton Research Capital',
    companyWebsite: 'https://gravitonresearch.com',
    industry: 'Quantitative Trading & HFT',
    title: 'Quantitative Developer Intern (C++)',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,75,000 - ₹2,50,000 / month',
    benefits: 'Guest house accommodation, round trip airfare, highest campus PPO conversion packages in India',
    applicationUrl: 'https://gravitonresearch.com/careers',
    deadline: new Date('2026-11-10'),
    description: 'Design and engineer ultra-low-latency market connectivity libraries, lock-free queues, and cache-optimized matching systems.',
    requirements: 'Top academic performers in CS/EE/Math in India. Mastery of C++17/20, STL, Computer Architecture, and OS.',
    tags: ['graviton', 'internship', 'gurugram', 'delhi-ncr', 'hft', 'c++', 'trading', 'india'],
  },
  {
    companyName: 'Quadeye',
    companyWebsite: 'https://quadeye.com',
    industry: 'Quantitative Trading & HFT',
    title: 'Software Developer Intern - High Frequency Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,50,000 - ₹2,25,000 / month',
    benefits: 'Fully paid accommodation, chef-prepared meals, top compensation tier',
    applicationUrl: 'https://quadeye.com/careers',
    deadline: new Date('2026-11-12'),
    description: 'Build algorithmic execution engines, network packet sniffers, and automated risk check pipelines operating at sub-microsecond speeds.',
    requirements: 'Undergraduate or master in CS/Math in India. World-class problem solving, C++, multithreading, and network protocols.',
    tags: ['quadeye', 'internship', 'gurugram', 'delhi-ncr', 'c++', 'hft', 'india'],
  },
  {
    companyName: 'WorldQuant',
    companyWebsite: 'https://worldquant.com',
    industry: 'Quantitative Finance',
    title: 'Quantitative Research Intern (BRAIN Platform)',
    type: OpportunityType.INTERNSHIP,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,20,000 - ₹1,75,000 / month',
    benefits: 'Alpha consultant stipend bonuses, cloud research cluster access, global research network',
    applicationUrl: 'https://worldquant.com/careers/',
    deadline: new Date('2026-11-20'),
    description: 'Develop mathematical predictive alphas, financial time-series models, and portfolio optimization strategies on the WorldQuant BRAIN platform.',
    requirements: 'Pursuing degree in Math, Physics, CS, or Finance in India. Strong statistical intuition, Python, and machine learning.',
    tags: ['worldquant', 'internship', 'mumbai', 'quantitative', 'math', 'python', 'india'],
  },
  {
    companyName: 'Barclays',
    companyWebsite: 'https://barclays.com/careers',
    industry: 'Investment Banking & FinTech',
    title: 'Technology Developer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Pune, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹75,000 - ₹95,000 / month',
    benefits: 'High PPO conversion, medical insurance, transport facilities',
    applicationUrl: 'https://home.barclays/careers/our-programmes/undergraduates-and-graduates/',
    deadline: new Date('2026-11-25'),
    description: 'Develop core banking platforms, risk management engines, and cloud financial services supporting Barclays UK and international customers.',
    requirements: 'B.Tech/BE in CS/IT in India graduating in 2027. Strong Java, Spring Boot, Angular/React, and relational databases.',
    tags: ['barclays', 'internship', 'pune', 'banking', 'java', 'fintech', 'india'],
  },
  {
    companyName: 'Deutsche Bank',
    companyWebsite: 'https://db.com/careers',
    industry: 'Investment Banking & FinTech',
    title: 'Graduate Technology Intern - Corporate Bank Technology',
    type: OpportunityType.INTERNSHIP,
    location: 'Pune, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹70,000 - ₹90,000 / month',
    benefits: 'High PPO conversion rate, comprehensive health coverage, training workshops',
    applicationUrl: 'https://careers.db.com/students-graduates/',
    deadline: new Date('2026-11-28'),
    description: 'Work on modernizing trade finance platforms, payment transaction switches, and regulatory reporting pipelines on Google Cloud.',
    requirements: 'Pursuing CS/IT degree in India. Good knowledge of Java, Python, GCP, and microservices.',
    tags: ['deutsche-bank', 'internship', 'pune', 'fintech', 'java', 'gcp', 'india'],
  },
  {
    companyName: 'Citi',
    companyWebsite: 'https://citigroup.com/careers',
    industry: 'Banking & Financial Services',
    title: 'Technology Summer Analyst Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹75,000 - ₹95,000 / month',
    benefits: 'Health insurance, learning portal access, return offer opportunity',
    applicationUrl: 'https://careers.citigroup.com/students-and-graduates/',
    deadline: new Date('2026-11-20'),
    description: 'Build enterprise banking APIs, fraud prevention engines, and wealth management mobile backends across Citi’s global centers.',
    requirements: 'Undergraduate engineering student graduating in 2027 in India. Proficiency in Java, Python, or Web frameworks.',
    tags: ['citi', 'internship', 'chennai', 'banking', 'fintech', 'java', 'india'],
  },
  {
    companyName: 'BlackRock',
    companyWebsite: 'https://blackrock.com/careers',
    industry: 'Asset Management & FinTech',
    title: 'Software Engineering Summer Analyst (Aladdin Platform)',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹85,000 - ₹1,10,000 / month',
    benefits: 'Aladdin platform training, wellness benefits, high PPO conversion',
    applicationUrl: 'https://careers.blackrock.com/early-careers',
    deadline: new Date('2026-11-15'),
    description: 'Develop Aladdin—the world’s premier investment and risk management operating system used by sovereign wealth funds and institutional investors.',
    requirements: 'Pursuing B.Tech/M.Tech in CS/IT in India graduating in 2027. Strong Java, C++, TypeScript, or Python.',
    tags: ['blackrock', 'internship', 'gurugram', 'delhi-ncr', 'aladdin', 'fintech', 'java', 'india'],
  },

  // =========================================================================
  // 3. TOP INDIAN TECH UNICORNS & HIGH-GROWTH STARTUPS
  // =========================================================================
  {
    companyName: 'Slice',
    companyWebsite: 'https://sliceit.com',
    industry: 'FinTech & Digital Banking',
    title: 'Software Engineering Intern - Core Banking & Payments',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹60,000 - ₹85,000 / month',
    benefits: 'Fast-paced startup culture, health coverage, pre-placement offer pathway',
    applicationUrl: 'https://sliceit.com/careers',
    deadline: new Date('2026-11-20'),
    description: 'Build high-throughput core banking microservices, UPI transaction switches, and real-time fraud scoring engines.',
    requirements: 'Strong CS fundamentals, proficiency in Golang, Java, or Node.js, and experience with PostgreSQL.',
    tags: ['slice', 'internship', 'bengaluru', 'fintech', 'upi', 'golang', 'india'],
  },
  {
    companyName: 'Paytm',
    companyWebsite: 'https://paytm.com',
    industry: 'FinTech & Payments',
    title: 'Software Engineer Intern - Soundbox & Payments Switch',
    type: OpportunityType.INTERNSHIP,
    location: 'Noida, Uttar Pradesh, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹70,000 / month',
    benefits: 'Health insurance, transport assistance, high conversion rate to SDE-1',
    applicationUrl: 'https://paytm.com/careers/',
    deadline: new Date('2026-11-25'),
    description: 'Work on India’s largest merchant payment switch, UPI QR code processing backends, and Soundbox IoT firmware communication.',
    requirements: 'B.Tech/BE in CS/IT/ECE in India. Knowledge of Java, Spring Boot, Kafka, and Redis caching.',
    tags: ['paytm', 'internship', 'noida', 'delhi-ncr', 'fintech', 'payments', 'java', 'india'],
  },
  {
    companyName: 'Nykaa',
    companyWebsite: 'https://nykaa.com',
    industry: 'Beauty & Fashion E-Commerce',
    title: 'Software Development Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Product discounts, cafeteria, learning stipend, return offer path',
    applicationUrl: 'https://nykaa.com/careers',
    deadline: new Date('2026-11-22'),
    description: 'Build recommendation algorithms, personalized search rankers, and checkout systems for India’s premier beauty platform.',
    requirements: 'Undergraduate student in CS/IT in India. Good knowledge of Node.js, React, Java, or Python and MySQL.',
    tags: ['nykaa', 'internship', 'mumbai', 'ecommerce', 'nodejs', 'react', 'india'],
  },
  {
    companyName: 'Ola',
    companyWebsite: 'https://olacabs.com',
    industry: 'Mobility & EV Tech',
    title: 'Software Engineer Intern - Ride Dispatch & Map Algorithms',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹55,000 - ₹80,000 / month',
    benefits: 'Ola ride credits, free meals, high-growth startup environment',
    applicationUrl: 'https://olacabs.com/careers',
    deadline: new Date('2026-11-18'),
    description: 'Design geospatial routing engines, dynamic surge pricing models, and Ola Maps spatial query optimizers.',
    requirements: 'Solid grasp of Data Structures, Algorithms, Java/Go, and distributed key-value stores.',
    tags: ['ola', 'internship', 'bengaluru', 'mobility', 'maps', 'golang', 'india'],
  },
  {
    companyName: 'ShareChat',
    companyWebsite: 'https://sharechat.com',
    industry: 'Social Media & Short Video',
    title: 'Machine Learning & SDE Intern - Feed Ranking',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹70,000 - ₹95,000 / month',
    benefits: 'Work from anywhere in India, MacBook Pro, learning stipend, return offer pathway',
    applicationUrl: 'https://sharechat.com/careers',
    deadline: new Date('2026-11-28'),
    description: 'Build deep learning recommendation models for video feeds processing billions of daily impressions across 15+ Indian regional languages.',
    requirements: 'Strong proficiency in Python, PyTorch/TensorFlow, Golang, and deep recommendation networks.',
    tags: ['sharechat', 'internship', 'bengaluru', 'remote', 'machine-learning', 'nlp', 'india'],
  },
  {
    companyName: 'Lenskart',
    companyWebsite: 'https://lenskart.com',
    industry: 'Eyewear & AI Retail',
    title: 'Computer Vision & Software Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Faridabad, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹70,000 / month',
    benefits: 'Free eyewear allowances, shuttle transport from Delhi NCR, PPO conversion',
    applicationUrl: 'https://lenskart.com/careers',
    deadline: new Date('2026-11-30'),
    description: 'Develop 3D face mesh tracking, virtual try-on rendering pipelines, and automated optical factory sorting software.',
    requirements: 'B.Tech/M.Tech in CS/Data Science in India. Knowledge of OpenCV, PyTorch, C++, and React Native.',
    tags: ['lenskart', 'internship', 'faridabad', 'delhi-ncr', 'computer-vision', '3d', 'india'],
  },
  {
    companyName: 'Freshworks',
    companyWebsite: 'https://freshworks.com',
    industry: 'SaaS & Customer Support',
    title: 'Software Product Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Modern campus amenities, transport, return offer path, learning stipend',
    applicationUrl: 'https://freshworks.com/company/careers/',
    deadline: new Date('2026-11-20'),
    description: 'Build AI-powered ticketing workflows, omnichannel CRM tools, and cloud developer platforms serving 60,000+ businesses globally.',
    requirements: 'Pursuing CS/IT degree in India. Experience with Ruby on Rails, Java, Node.js, or React.',
    tags: ['freshworks', 'internship', 'chennai', 'saas', 'ruby', 'react', 'india'],
  },
  {
    companyName: 'Zoho',
    companyWebsite: 'https://zoho.com',
    industry: 'Cloud Software & Productivity',
    title: 'Software Developer Intern - Cloud Infrastructure',
    type: OpportunityType.INTERNSHIP,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹40,000 - ₹60,000 / month',
    benefits: 'Free accommodation, gourmet dining, calm culture, high full-time offer rate',
    applicationUrl: 'https://zoho.com/careers/',
    deadline: new Date('2026-12-01'),
    description: 'Work on proprietary database engines, email storage servers, and web office applications across Zoho’s self-managed data centers.',
    requirements: 'Enrolled in engineering in India. Strong C, C++, or Java fundamentals and understanding of OS and Networks.',
    tags: ['zoho', 'internship', 'chennai', 'cloud', 'c++', 'database', 'india'],
  },
  {
    companyName: 'Devfolio',
    companyWebsite: 'https://devfolio.co',
    industry: 'Developer Tools & Web3',
    title: 'Full Stack Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Work from anywhere in India, crypto/Web3 hackathon tickets, hardware allowance',
    applicationUrl: 'https://devfolio.co/careers',
    deadline: new Date('2026-11-25'),
    description: 'Build developer hackathon tooling, automated judging systems, and Web3 portfolio builders empowering 500,000+ builders.',
    requirements: 'Proficiency in TypeScript, Next.js, Node.js, GraphQL, and PostgreSQL.',
    tags: ['devfolio', 'internship', 'bengaluru', 'remote', 'typescript', 'nextjs', 'india'],
  },
  {
    companyName: 'BharatPe',
    companyWebsite: 'https://bharatpe.com',
    industry: 'FinTech & Merchant Lending',
    title: 'Backend Software Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹70,000 / month',
    benefits: 'Health insurance, meal coupons, fast PPO conversion',
    applicationUrl: 'https://bharatpe.com/careers',
    deadline: new Date('2026-11-18'),
    description: 'Build UPI settlement microservices, merchant loan underwriting engines, and POS transaction switches.',
    requirements: 'B.Tech student in CS/IT in India. Solid experience in Golang, Node.js, and MySQL/PostgreSQL.',
    tags: ['bharatpe', 'internship', 'gurugram', 'delhi-ncr', 'fintech', 'golang', 'india'],
  },

  // =========================================================================
  // 4. TOP RESEARCH FELLOWSHIPS & ACADEMIC LABS IN INDIA
  // =========================================================================
  {
    companyName: 'IIT Madras',
    companyWebsite: 'https://iitm.ac.in',
    industry: 'Higher Education & Research',
    title: 'IIT Madras Summer Fellowship Programme 2027',
    type: OpportunityType.RESEARCH,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹15,000 / month stipend + Campus Hostel',
    benefits: 'Access to Robert Bosch Centre for Data Science and AI (RBCDSAI) and IITM Research Park',
    applicationUrl: 'https://sfp.iitm.ac.in/',
    deadline: new Date('2026-11-28'),
    description: '2-month summer research fellowship at IIT Madras working on Data Science, Deep Learning, Biomedical AI, and Quantum Computing.',
    requirements: 'Pre-final year undergraduate students (B.E./B.Tech) with exceptional academic performance in India.',
    tags: ['iit-madras', 'research', 'chennai', 'ai', 'data-science', 'fellowship', 'india'],
  },
  {
    companyName: 'IIT Delhi',
    companyWebsite: 'https://iitd.ac.in',
    industry: 'Higher Education & Research',
    title: 'IIT Delhi Summer Undergraduate Research Award (SURA) 2027',
    type: OpportunityType.RESEARCH,
    location: 'New Delhi, Delhi NCR, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹15,000 / month stipend + Hostel Stay',
    benefits: 'Certificate of excellence, full access to IIT Delhi supercomputing and nanotechnology facilities',
    applicationUrl: 'https://iitd.ac.in/research/summer-internship',
    deadline: new Date('2026-11-20'),
    description: 'Work with IIT Delhi faculty at the Yardi School of Artificial Intelligence and CSE Department on robotics, LLMs, and formal methods.',
    requirements: 'Enrolled in 2nd or 3rd year engineering at accredited Indian universities.',
    tags: ['iit-delhi', 'research', 'new-delhi', 'delhi-ncr', 'ai', 'robotics', 'india'],
  },
  {
    companyName: 'IIT Kanpur',
    companyWebsite: 'https://iitk.ac.in',
    industry: 'Higher Education & Research',
    title: 'IIT Kanpur SURGE Summer Research Fellowship 2027',
    type: OpportunityType.RESEARCH,
    location: 'Kanpur, Uttar Pradesh, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹12,500 - ₹20,000 / month stipend + Hostel',
    benefits: 'Publication opportunities, certificate signed by Dean of Academic Affairs, campus accommodation',
    applicationUrl: 'https://iitk.ac.in/surge/',
    deadline: new Date('2026-11-30'),
    description: 'Conduct fundamental research in Cyber Security (C3iHub), Autonomous Drones, and Theoretical Computer Science at IIT Kanpur.',
    requirements: 'B.Tech/BE students in India completing 2nd or 3rd year with CGPA >= 8.5/10.',
    tags: ['iit-kanpur', 'research', 'kanpur', 'cybersecurity', 'drones', 'india'],
  },
  {
    companyName: 'Tata Institute of Fundamental Research (TIFR)',
    companyWebsite: 'https://tifr.res.in',
    industry: 'Fundamental Science Research',
    title: 'TIFR Visiting Students Research Programme (VSRP) 2027',
    type: OpportunityType.RESEARCH,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹15,000 / month + Free Campus Accommodation & Travel',
    benefits: 'Direct access to TIFR Colaba sea-facing campus, supercomputer clusters, fast track for PhD admissions',
    applicationUrl: 'https://tifr.res.in/~vsrp/',
    deadline: new Date('2026-12-05'),
    description: 'Prestigious research programme at India’s premier fundamental research institute in Theoretical Computer Science, Quantum Information, and Astrophysics.',
    requirements: 'Pre-final year students of B.Tech, M.Sc, or Integrated Master’s in India in CS, Physics, or Math.',
    tags: ['tifr', 'research', 'mumbai', 'theoretical-cs', 'quantum', 'physics', 'india'],
  },
  {
    companyName: 'CDAC (Centre for Development of Advanced Computing)',
    companyWebsite: 'https://cdac.in',
    industry: 'National Supercomputing & Gov Tech',
    title: 'Supercomputing & AI Research Project Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Pune, Maharashtra, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹20,000 - ₹35,000 / month stipend',
    benefits: 'Hands-on access to PARAM supercomputers, Government of India certification',
    applicationUrl: 'https://cdac.in/index.aspx?id=internship',
    deadline: new Date('2026-11-25'),
    description: 'Build parallel MPI algorithms, GPU clusters, and High-Performance Computing (HPC) software on India’s National Supercomputing Mission infrastructure.',
    requirements: 'Enrolled in B.Tech/M.Tech in CS/IT in India. Strong C, C++, MPI, OpenMP, and Linux.',
    tags: ['cdac', 'hpc', 'supercomputing', 'pune', 'internship', 'mpi', 'india'],
  },
  {
    companyName: 'ISRO (Indian Space Research Organisation)',
    companyWebsite: 'https://isro.gov.in',
    industry: 'Aerospace & Satellite Tech',
    title: 'Student Project Intern - Satellite Image Processing & AI',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: 'Government Stipend + Access to ISRO Satellite Datasets',
    benefits: 'Official ISRO Project Completion Certificate, guidance from ISRO Space Scientists',
    applicationUrl: 'https://isro.gov.in/Internship.html',
    deadline: new Date('2026-12-01'),
    description: 'Work with ISRO Satellite Centre (URSC) on satellite telemetry processing, computer vision for earth observation, and space robotics simulations.',
    requirements: 'Citizen of India pursuing B.Tech/M.Tech in CS/ECE/Aerospace in an AICTE recognized university (Minimum 75% marks).',
    tags: ['isro', 'space', 'satellite', 'internship', 'bengaluru', 'computer-vision', 'india'],
  },
];

async function main() {
  console.log('🚀 Running Massive Indian Opportunities Ingestion...');
  console.log(`Ingesting ${MASSIVE_INDIAN_CATALOG.length} additional curated Indian tech openings...`);

  let addedCount = 0;
  let updatedCount = 0;

  for (const opp of MASSIVE_INDIAN_CATALOG) {
    // 1. Get or create company
    let company = await prisma.company.findFirst({
      where: { name: { equals: opp.companyName, mode: 'insensitive' } },
    });

    if (!company) {
      company = await prisma.company.create({
        data: {
          name: opp.companyName,
          websiteUrl: opp.companyWebsite,
          industry: opp.industry,
          description: `Leading organization with top-tier technology and engineering operations in India.`,
        },
      });
    }

    // 2. Upsert opportunity
    const existing = await prisma.opportunity.findFirst({
      where: {
        companyId: company.id,
        title: opp.title,
      },
    });

    if (!existing) {
      await prisma.opportunity.create({
        data: {
          title: opp.title,
          type: opp.type,
          companyId: company.id,
          location: opp.location,
          remoteType: opp.remoteType,
          salaryRange: opp.salaryRange,
          benefits: opp.benefits,
          applicationUrl: opp.applicationUrl,
          deadline: opp.deadline,
          description: opp.description,
          requirements: opp.requirements,
          tags: opp.tags,
          isActive: true,
          isArchived: false,
        },
      });
      addedCount++;
    } else {
      await prisma.opportunity.update({
        where: { id: existing.id },
        data: {
          location: opp.location,
          salaryRange: opp.salaryRange,
          benefits: opp.benefits,
          applicationUrl: opp.applicationUrl,
          deadline: opp.deadline,
          description: opp.description,
          requirements: opp.requirements,
          tags: opp.tags,
          isActive: true,
          isArchived: false,
        },
      });
      updatedCount++;
    }
  }

  console.log(`\n✓ Ingested: ${addedCount} new, ${updatedCount} updated.`);

  // Print final database summary
  const total = await prisma.opportunity.count();
  const internships = await prisma.opportunity.count({ where: { type: OpportunityType.INTERNSHIP } });
  const hackathons = await prisma.opportunity.count({ where: { type: OpportunityType.HACKATHON } });
  const fellowships = await prisma.opportunity.count({ where: { type: OpportunityType.FELLOWSHIP } });
  const research = await prisma.opportunity.count({ where: { type: OpportunityType.RESEARCH } });

  console.log('\n📊 Comprehensive Indian Opportunities Breakdown:');
  console.log(`- 💼 Internships in India: ${internships}`);
  console.log(`- 🏆 Hackathons in India: ${hackathons}`);
  console.log(`- 🎓 Fellowships in India: ${fellowships}`);
  console.log(`- 🔬 Research Programs in India: ${research}`);
  console.log(`- 🌟 Total Indian Opportunities: ${total}`);

  // Trigger AI enrichment on any pending items
  console.log('\n🧠 Draining AI enrichment queue for newly added Indian opportunities...');
  const enrichResult = await EnrichmentEngine.drainAllPending();
  console.log(`✓ AI Enrichment complete! Processed: ${enrichResult.processed}, Success: ${enrichResult.success}, Failed: ${enrichResult.failed}`);
}

main()
  .then(() => {
    console.log('\n🎉 Comprehensive Indian Opportunities Catalog successfully populated and 100% AI enriched!');
    process.exit(0);
  })
  .catch((err) => {
    console.error('Fatal error during massive catalog ingestion:', err);
    process.exit(1);
  });
