import { prisma } from '../lib/db';
import { OpportunityType, RemoteType } from '../lib/generated/prisma/enums';
import { EnrichmentEngine } from '../lib/ai/enrichment-engine';

interface IndianOpportunitySeed {
  companyName: string;
  companyWebsite: string;
  industry: string;
  title: string;
  type: OpportunityType;
  location: string;
  remoteType: RemoteType;
  salaryRange: string;
  benefits?: string;
  applicationUrl: string;
  deadline: Date;
  description: string;
  requirements: string;
  tags: string[];
}

const ALL_INDIAN_OPPORTUNITIES: IndianOpportunitySeed[] = [
  // ==========================================
  // 1. TOP MNC TECH HUBS & GCCs IN INDIA
  // ==========================================
  {
    companyName: 'Google',
    companyWebsite: 'https://careers.google.com',
    industry: 'Technology & Cloud',
    title: 'Software Engineering Intern, Summer 2027',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,25,000 - ₹1,50,000 / month',
    benefits: 'High PPO conversion, gourmet meals, shuttle service, health insurance',
    applicationUrl: 'https://careers.google.com/jobs/results/software-engineering-intern-bangalore/',
    deadline: new Date('2026-12-15'),
    description: 'Work on core Google products including Google Search, Android, Google Pay India, and Google Cloud platform services.',
    requirements: 'Enrolled in Bachelor or Master CS/IT degree in India graduating in 2027 or 2028. Strong Data Structures, Algorithms, C++, Java, or Python.',
    tags: ['google', 'internship', 'bengaluru', 'swe', 'algorithms', 'india'],
  },
  {
    companyName: 'Google',
    companyWebsite: 'https://careers.google.com',
    industry: 'Technology & Cloud',
    title: 'STEP Internship 2027 (Student Training in Engineering Program)',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹85,000 - ₹1,15,000 / month',
    benefits: 'Relocation assistance, mentorship, return offer pathway, learning stipends',
    applicationUrl: 'https://buildyourfuture.withgoogle.com/step',
    deadline: new Date('2026-11-30'),
    description: 'Developmental software internship for 1st & 2nd year undergraduate students across India with direct mentorship from Google Engineers.',
    requirements: 'Currently enrolled in an undergraduate degree in Computer Science or related field in India; graduating in 2028 or 2029.',
    tags: ['google', 'step', 'internship', 'hyderabad', 'first-year', 'second-year', 'india'],
  },
  {
    companyName: 'Microsoft',
    companyWebsite: 'https://careers.microsoft.com',
    industry: 'Technology & Cloud',
    title: 'Software Engineering Intern - Microsoft India Development Center (IDC)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,25,000 / month',
    benefits: 'Housing allowance, wellness reimbursement, Microsoft Surface hardware, medical coverage',
    applicationUrl: 'https://careers.microsoft.com/us/en/job/1689234/software-engineering-intern',
    deadline: new Date('2026-11-20'),
    description: 'Build enterprise cloud architectures, generative AI copilots, and distributed systems powering Microsoft Azure and Office 365.',
    requirements: 'Pursuing B.Tech/M.Tech/Dual Degree in CS/IT or relevant engineering discipline in India. Strong C++, C#, Java, or Python foundations.',
    tags: ['microsoft', 'idc', 'internship', 'bengaluru', 'azure', 'copilot', 'india'],
  },
  {
    companyName: 'Microsoft',
    companyWebsite: 'https://careers.microsoft.com',
    industry: 'Technology & Cloud',
    title: 'Software Engineering Intern - Cloud & AI Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,25,000 / month',
    benefits: 'Cab transport, fitness perks, relocation allowance, high PPO conversion',
    applicationUrl: 'https://careers.microsoft.com/us/en/job/1689235/software-engineering-intern-hyderabad',
    deadline: new Date('2026-11-25'),
    description: 'Work on hyper-scale infrastructure, security services, and developer tooling at Microsoft IDC Hyderabad campus.',
    requirements: 'B.Tech / M.Tech students graduating in 2027 or 2028. Strong algorithm problem-solving skills.',
    tags: ['microsoft', 'internship', 'hyderabad', 'cloud', 'ai', 'india'],
  },
  {
    companyName: 'Amazon',
    companyWebsite: 'https://amazon.jobs',
    industry: 'E-Commerce & Cloud',
    title: 'Software Development Engineer (SDE) Intern - Summer 2027',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,10,000 / month',
    benefits: 'Housing allowance, round-trip travel reimbursement, Amazon Prime, high return offer rate',
    applicationUrl: 'https://amazon.jobs/en/jobs/2589012/software-development-engineer-intern',
    deadline: new Date('2026-11-30'),
    description: 'Design and build high-throughput backend services powering AWS cloud, Amazon.in retail platform, and Alexa Voice AI.',
    requirements: 'Enrolled in an Indian university degree in Computer Science; graduation in 2027 or 2028. Strong Java, C++, or Go.',
    tags: ['amazon', 'sde', 'internship', 'bengaluru', 'aws', 'backend', 'india'],
  },
  {
    companyName: 'Amazon',
    companyWebsite: 'https://amazon.jobs',
    industry: 'E-Commerce & Cloud',
    title: 'Software Development Engineer (SDE) Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,10,000 / month',
    benefits: 'Housing stipend, meal coupons, relocation assistance, PPO track',
    applicationUrl: 'https://amazon.jobs/en/jobs/2589013/software-development-engineer-intern-hyderabad',
    deadline: new Date('2026-12-05'),
    description: 'Build automated supply chain optimization models, logistics engines, and payment gateways for global and Indian customers.',
    requirements: 'B.Tech/BE/M.Tech students in India graduating 2027/2028. Solid grasp of OOP, OS, and DBMS concepts.',
    tags: ['amazon', 'sde', 'internship', 'hyderabad', 'java', 'india'],
  },
  {
    companyName: 'Amazon',
    companyWebsite: 'https://amazon.jobs',
    industry: 'E-Commerce & Cloud',
    title: 'Applied Science / Machine Learning Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,30,000 / month',
    benefits: 'Compute cluster access, GPU quotas, research mentorship, publication sponsorship',
    applicationUrl: 'https://amazon.jobs/en/jobs/applied-science-intern-india',
    deadline: new Date('2026-11-15'),
    description: 'Conduct applied research in NLP, Computer Vision, and Generative AI to improve search ranking and catalog intelligence.',
    requirements: 'Master or PhD students (or exceptional final-year B.Tech) in CS, ML, or Math in India. Proficiency in PyTorch, JAX, or TensorFlow.',
    tags: ['amazon', 'machine-learning', 'internship', 'bengaluru', 'nlp', 'pytorch', 'india'],
  },
  {
    companyName: 'Apple',
    companyWebsite: 'https://apple.com/careers',
    industry: 'Consumer Tech & Hardware',
    title: 'Software Engineering Intern - Maps & Core OS',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,20,000 / month',
    benefits: 'Apple product discounts, relocation assistance, health coverage, executive mentorship',
    applicationUrl: 'https://jobs.apple.com/en-in/details/200542312/software-engineering-intern',
    deadline: new Date('2026-11-28'),
    description: 'Work with the Apple Maps and Core OS engineering teams in Hyderabad on geospatial algorithms, routing graph pipelines, and iOS frameworks.',
    requirements: 'Enrolled in Computer Science or related degree in India. Strong C++, Swift, Python, and data structures proficiency.',
    tags: ['apple', 'internship', 'hyderabad', 'maps', 'c++', 'swift', 'india'],
  },
  {
    companyName: 'Adobe',
    companyWebsite: 'https://adobe.com/careers',
    industry: 'Creative & Digital Software',
    title: 'Software Development Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Noida, Uttar Pradesh, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,00,000 / month',
    benefits: 'Creative Cloud subscription, wellness reimbursement, shuttle transport, PPO conversion',
    applicationUrl: 'https://adobe.wd5.myworkdayjobs.com/adobe-careers/job/Noida/SDE-Intern',
    deadline: new Date('2026-11-25'),
    description: 'Develop features for Adobe Creative Cloud, Acrobat Document Cloud, and Adobe Firefly generative AI tools.',
    requirements: 'B.Tech/Dual Degree students graduating 2027. Strong C++, Java, or Web technologies (WebAssembly, WebGL).',
    tags: ['adobe', 'internship', 'noida', 'delhi-ncr', 'c++', 'firefly', 'india'],
  },
  {
    companyName: 'Adobe',
    companyWebsite: 'https://adobe.com/careers',
    industry: 'Creative & Digital Software',
    title: 'Computer Science Research Intern',
    type: OpportunityType.RESEARCH,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,20,000 / month',
    benefits: 'Direct collaboration with Adobe Research Scientists, patent filing bonuses',
    applicationUrl: 'https://research.adobe.com/careers/',
    deadline: new Date('2026-12-01'),
    description: 'Perform cutting-edge research in generative imagery, diffusion models, 3D vision, and document understanding at Adobe Research India.',
    requirements: 'MS or PhD students in Computer Science, AI, or Mathematics in India. Top conference publications (CVPR, ICCV, NeurIPS) are a plus.',
    tags: ['adobe', 'research', 'bengaluru', 'computer-vision', 'ai', 'india'],
  },
  {
    companyName: 'Nvidia',
    companyWebsite: 'https://nvidia.com/careers',
    industry: 'AI, GPUs & Hardware',
    title: 'System Software Engineering Intern - GPU Computing & CUDA',
    type: OpportunityType.INTERNSHIP,
    location: 'Pune, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹95,000 - ₹1,20,000 / month',
    benefits: 'Nvidia stock purchase plan eligibility, high-end GPU workstations, mentorship',
    applicationUrl: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/India-Pune/Software-Intern',
    deadline: new Date('2026-11-18'),
    description: 'Optimize CUDA compilers, GPU device drivers, and AI acceleration runtimes (TensorRT) for LLM training and inference.',
    requirements: 'Pursuing Bachelor’s or Master’s in CS/ECE in India. Deep knowledge of C, C++, Computer Architecture, and Operating Systems.',
    tags: ['nvidia', 'internship', 'pune', 'cuda', 'c++', 'gpu', 'ai', 'india'],
  },
  {
    companyName: 'Nvidia',
    companyWebsite: 'https://nvidia.com/careers',
    industry: 'AI, GPUs & Hardware',
    title: 'Deep Learning Software Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,10,000 / month',
    benefits: 'DGX Cloud access, cutting-edge AI research environment, return offer pathway',
    applicationUrl: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/India-Bengaluru/Deep-Learning-Intern',
    deadline: new Date('2026-12-05'),
    description: 'Work on transformer architectures, NeMo framework, and AI model quantization for enterprise generative AI deployments.',
    requirements: 'Strong background in Deep Learning, PyTorch, CUDA, and high-performance Python/C++.',
    tags: ['nvidia', 'internship', 'bengaluru', 'deep-learning', 'pytorch', 'india'],
  },
  {
    companyName: 'Qualcomm',
    companyWebsite: 'https://qualcomm.com/careers',
    industry: 'Semiconductors & Wireless',
    title: 'Software Engineer Intern - Snapdragon AI & Modem Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹85,000 - ₹1,05,000 / month',
    benefits: 'Relocation allowance, comprehensive health cover, lab equipment access',
    applicationUrl: 'https://qualcomm.wd5.myworkdayjobs.com/External/job/Hyderabad-IND/Engineer-Intern',
    deadline: new Date('2026-11-30'),
    description: 'Design low-level software, 5G protocol stacks, and NPU firmware for Snapdragon mobile and automotive platforms.',
    requirements: 'B.Tech/M.Tech in CS/ECE/EEE in India. Proficiency in Embedded C, C++, Linux kernel, and Microcontrollers.',
    tags: ['qualcomm', 'internship', 'hyderabad', 'embedded', 'snapdragon', '5g', 'india'],
  },
  {
    companyName: 'Cisco',
    companyWebsite: 'https://cisco.com/careers',
    industry: 'Networking & Cybersecurity',
    title: 'Software Engineer Intern - Cloud & Network Security',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹90,000 - ₹1,10,000 / month',
    benefits: 'Fitness reimbursement, Cisco certifications coverage, hybrid flexibility',
    applicationUrl: 'https://jobs.cisco.com/jobs/SearchJobs/India-Software-Engineer-Intern',
    deadline: new Date('2026-12-10'),
    description: 'Build enterprise networking software, secure SD-WAN controllers, and cloud threat intelligence pipelines.',
    requirements: 'Enrolled in Computer Science/IT/ECE in India. Solid knowledge of TCP/IP, Computer Networks, Linux, and Python/Go/C++.',
    tags: ['cisco', 'internship', 'bengaluru', 'networking', 'security', 'python', 'india'],
  },
  {
    companyName: 'Intel',
    companyWebsite: 'https://intel.com/careers',
    industry: 'Semiconductors & Computing',
    title: 'Graduate Technical Intern - Silicon Architecture & Software',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹80,000 - ₹1,00,000 / month',
    benefits: 'Silicon design tools training, medical benefits, transport facilities',
    applicationUrl: 'https://jobs.intel.com/en/search-jobs/India/Intern',
    deadline: new Date('2026-11-20'),
    description: 'Validate hardware IP blocks, develop system firmware/BIOS, and write software benchmarks for Intel Xeon and Core processors.',
    requirements: 'Pursuing B.Tech/M.Tech in CS/ECE/VLSI in India. Knowledge of Verilog/VHDL, Python scripting, or C/C++.',
    tags: ['intel', 'internship', 'bengaluru', 'vlsi', 'silicon', 'c++', 'india'],
  },
  {
    companyName: 'AMD',
    companyWebsite: 'https://amd.com/careers',
    industry: 'Semiconductors & AI',
    title: 'Software Development Intern - ROCm & AI Software Ecosystem',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹85,000 - ₹1,05,000 / month',
    benefits: 'AMD hardware discounts, flexible work hours, learning allowance',
    applicationUrl: 'https://careers.amd.com/careers-home/jobs?keywords=intern&location=India',
    deadline: new Date('2026-11-28'),
    description: 'Contribute to AMD’s open-source ROCm GPU computing platform, PyTorch optimizations, and server AI accelerators.',
    requirements: 'Enrolled in Computer Science or Electrical Engineering in India. Strong C++, Python, and Linux systems background.',
    tags: ['amd', 'internship', 'hyderabad', 'rocm', 'gpu', 'ai', 'india'],
  },
  {
    companyName: 'Salesforce',
    companyWebsite: 'https://salesforce.com/careers',
    industry: 'Enterprise CRM & Cloud',
    title: 'Software Engineering Intern - Core Infrastructure',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,00,000 - ₹1,20,000 / month',
    benefits: 'Home office budget, comprehensive health benefits, volunteer time off, PPO opportunity',
    applicationUrl: 'https://salesforce.wd1.myworkdayjobs.com/External_Career_Site/job/India---Hyderabad/Software-Engineering-Intern',
    deadline: new Date('2026-11-15'),
    description: 'Build hyper-scale multi-tenant cloud architectures, database replication tools, and Einstein AI platform services.',
    requirements: 'Undergraduate student in CS/IT in India graduating in 2027. Strong Java, distributed systems, and SQL experience.',
    tags: ['salesforce', 'internship', 'hyderabad', 'java', 'cloud', 'einstein', 'india'],
  },
  {
    companyName: 'Intuit',
    companyWebsite: 'https://intuit.com/careers',
    industry: 'Financial Software',
    title: 'Software Engineering Intern (QuickBooks & TurboTax)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,15,000 / month',
    benefits: 'Health insurance, wellness stipend, free food and transport, return offer path',
    applicationUrl: 'https://jobs.intuit.com/job/bengaluru/software-engineer-intern',
    deadline: new Date('2026-11-30'),
    description: 'Work with the Intuit India development center building AI-driven fintech products serving millions of small businesses globally.',
    requirements: 'Pursuing Bachelor’s or Master’s in CS or related degree in India. Strong Java, Spring Boot, React, or Python skills.',
    tags: ['intuit', 'internship', 'bengaluru', 'fintech', 'java', 'react', 'india'],
  },
  {
    companyName: 'PayPal',
    companyWebsite: 'https://paypal.com/careers',
    industry: 'FinTech & Payments',
    title: 'Software Engineer Intern - Risk & Data Science',
    type: OpportunityType.INTERNSHIP,
    location: 'Chennai, Tamil Nadu, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹95,000 - ₹1,15,000 / month',
    benefits: 'Comprehensive health coverage, transportation, meal vouchers, PPO conversion',
    applicationUrl: 'https://paypal.wd1.myworkdayjobs.com/PayPal-Jobs/job/Chennai-India/Software-Engineer-Intern',
    deadline: new Date('2026-11-20'),
    description: 'Develop low-latency fraud detection algorithms, transaction risk engines, and secure payment tokenization microservices.',
    requirements: 'B.Tech/M.Tech CS students graduating in 2027. Strong programming in Java, Python, or Go and relational databases.',
    tags: ['paypal', 'internship', 'chennai', 'fintech', 'risk', 'fraud-detection', 'india'],
  },
  {
    companyName: 'Uber',
    companyWebsite: 'https://uber.com/careers',
    industry: 'Mobility & Logistics',
    title: 'Software Engineering Intern, Summer 2027',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,20,000 - ₹1,40,000 / month',
    benefits: 'Monthly Uber ride credits, housing allowance, health insurance, high PPO conversion',
    applicationUrl: 'https://uber.com/careers/internships-india',
    deadline: new Date('2026-11-25'),
    description: 'Build real-time dispatch matching engines, map intelligence systems, and payment infrastructure for Uber globally.',
    requirements: 'Undergraduate student in Computer Science graduating in 2027. Strong coding in Golang, Java, or Python and system design basics.',
    tags: ['uber', 'internship', 'hyderabad', 'golang', 'maps', 'distributed-systems', 'india'],
  },
  {
    companyName: 'Atlassian',
    companyWebsite: 'https://atlassian.com/careers',
    industry: 'Enterprise Software & Collaboration',
    title: 'Software Engineering Intern (India R&D Center)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹1,00,000 / month',
    benefits: 'Work from anywhere in India, home office setup budget, wellness allowance',
    applicationUrl: 'https://atlassian.com/careers/students',
    deadline: new Date('2026-11-20'),
    description: 'Build enterprise collaboration software including Jira, Confluence, and Loom used by millions of development teams globally.',
    requirements: 'Pursuing Bachelor’s or Master’s in Computer Science in India; graduating in 2027 or 2028. Experience with React, Java, or Kotlin.',
    tags: ['atlassian', 'internship', 'bengaluru', 'remote', 'react', 'java', 'india'],
  },
  {
    companyName: 'Goldman Sachs',
    companyWebsite: 'https://goldmansachs.com/careers',
    industry: 'Investment Banking & FinTech',
    title: 'Summer Analyst Engineering Intern 2027',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,00,000 - ₹1,25,000 / month',
    benefits: 'High PPO conversion to full-time Analyst, health coverage, executive mentorship',
    applicationUrl: 'https://goldmansachs.com/careers/students/programs/summer-analyst-program.html',
    deadline: new Date('2026-11-15'),
    description: 'Develop low-latency algorithmic trading systems, portfolio risk engines, and financial analytics platforms.',
    requirements: 'Penultimate year undergraduate or master student in India. Strong analytical skills, C++, Java, or Python, and DSA.',
    tags: ['goldman-sachs', 'internship', 'bengaluru', 'fintech', 'quantitative', 'algorithms', 'india'],
  },
  {
    companyName: 'Morgan Stanley',
    companyWebsite: 'https://morganstanley.com/careers',
    industry: 'Investment Banking & FinTech',
    title: 'Technology Summer Analyst Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹90,000 - ₹1,10,000 / month',
    benefits: 'Relocation assistance, comprehensive healthcare, financial modeling workshops',
    applicationUrl: 'https://morganstanley.com/careers/students-and-graduates',
    deadline: new Date('2026-11-22'),
    description: 'Build distributed cloud microservices, market data feeds, and wealth management software for global financial exchanges.',
    requirements: 'Pursuing Computer Science or related degree in India. Strong understanding of OOP, Data Structures, and SQL.',
    tags: ['morgan-stanley', 'internship', 'mumbai', 'fintech', 'java', 'sql', 'india'],
  },
  {
    companyName: 'JPMorgan Chase',
    companyWebsite: 'https://jpmorganchase.com/careers',
    industry: 'Banking & Financial Services',
    title: 'Software Engineer Summer Intern (SEP)',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹85,000 - ₹1,05,000 / month',
    benefits: 'High PPO rate, learning & development allowances, medical insurance',
    applicationUrl: 'https://careers.jpmorgan.com/us/en/students/programs/software-engineer-summer-internship',
    deadline: new Date('2026-11-18'),
    description: 'Work on mission-critical payments processing, cybersecurity monitoring, and cloud-native financial applications.',
    requirements: 'B.Tech/BE students in India graduating in 2027. Strong Java, Spring, React, or Python and computer science fundamentals.',
    tags: ['jpmorgan', 'internship', 'bengaluru', 'fintech', 'java', 'spring', 'india'],
  },
  {
    companyName: 'DE Shaw',
    companyWebsite: 'https://deshaw.com',
    industry: 'Quantitative Hedge Fund & FinTech',
    title: 'Software Developer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,50,000 - ₹2,00,000 / month',
    benefits: 'Premium housing accommodation, daily gourmet dining, travel reimbursement, highest compensation tier',
    applicationUrl: 'https://deshawindia.com/careers',
    deadline: new Date('2026-11-10'),
    description: 'Build ultra-low-latency electronic trading platforms, quantitative modeling tools, and high-performance financial data engines.',
    requirements: 'Top-tier academic record in Computer Science, Math, or Physics in India. Exceptional Data Structures, Algorithms, and C++/Python.',
    tags: ['de-shaw', 'internship', 'hyderabad', 'quantitative', 'c++', 'high-frequency-trading', 'india'],
  },
  {
    companyName: 'Tower Research Capital',
    companyWebsite: 'https://tower-research.com',
    industry: 'High Frequency Trading',
    title: 'Quantitative Software Developer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹1,50,000 - ₹2,25,000 / month',
    benefits: 'Luxury guest house stay, round-trip airfare, PPO fast track, top-tier compensation',
    applicationUrl: 'https://tower-research.com/careers',
    deadline: new Date('2026-11-12'),
    description: 'Develop nanosecond-latency network drivers, Linux kernel bypass software, and real-time execution algorithms for global electronic markets.',
    requirements: 'Pursuing B.Tech/M.Tech in CS/EE in India. World-class mastery of modern C++ (C++20), lock-free programming, and CPU caches.',
    tags: ['tower-research', 'internship', 'gurugram', 'delhi-ncr', 'c++', 'hft', 'india'],
  },

  // ==========================================
  // 2. TOP INDIAN TECH UNICORNS & STARTUPS
  // ==========================================
  {
    companyName: 'Flipkart',
    companyWebsite: 'https://flipkart.com',
    industry: 'E-Commerce & Logistics',
    title: 'Software Development Engineer (SDE) Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹60,000 - ₹80,000 / month',
    benefits: 'Shopping discounts, transport allowance, health insurance, PPO opportunity',
    applicationUrl: 'https://flipkartcareers.com',
    deadline: new Date('2026-11-20'),
    description: 'Build distributed catalog search, high-volume checkout microservices, and warehouse automation for India’s premier e-commerce platform.',
    requirements: 'B.Tech/BE in CS/IT in India graduating in 2027. Proficiency in Java, Dropwizard, Kafka, and Redis.',
    tags: ['flipkart', 'internship', 'bengaluru', 'sde', 'java', 'ecommerce', 'india'],
  },
  {
    companyName: 'Swiggy',
    companyWebsite: 'https://swiggy.com',
    industry: 'FoodTech & Quick Commerce',
    title: 'Software Engineer Intern - Consumer Apps & Logistics',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Remote flexibility, Swiggy One perks, learning budget, PPO conversion',
    applicationUrl: 'https://careers.swiggy.com',
    deadline: new Date('2026-11-25'),
    description: 'Work on real-time delivery assignment algorithms, dynamic pricing engines, and Instamart quick-commerce checkout flows.',
    requirements: 'Comfortable with Golang, Java, or React Native. Strong analytical thinking and clean code design.',
    tags: ['swiggy', 'internship', 'bengaluru', 'remote', 'golang', 'quick-commerce', 'india'],
  },
  {
    companyName: 'Zomato',
    companyWebsite: 'https://zomato.com',
    industry: 'FoodTech & Hyperlocal',
    title: 'Software Development Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹60,000 - ₹85,000 / month',
    benefits: 'Free meals, fun campus environment, pre-placement offer opportunity',
    applicationUrl: 'https://zomato.com/careers',
    deadline: new Date('2026-11-18'),
    description: 'Build high-scale backend microservices and mobile application features for Zomato delivery and Blinkit quick commerce.',
    requirements: 'Undergraduate student in CS/IT in India. Experience in PHP/Go/Node.js, MySQL, and distributed caching.',
    tags: ['zomato', 'internship', 'gurugram', 'delhi-ncr', 'backend', 'golang', 'india'],
  },
  {
    companyName: 'Groww',
    companyWebsite: 'https://groww.in',
    industry: 'FinTech & Wealth Management',
    title: 'Software Engineering Intern - Stock Trading & Mutual Funds',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹60,000 - ₹90,000 / month',
    benefits: 'Free lunch and snacks, health insurance, direct impact on millions of Indian retail investors',
    applicationUrl: 'https://groww.in/careers',
    deadline: new Date('2026-11-22'),
    description: 'Build low-latency order placement pipelines connecting to Indian stock exchanges (NSE/BSE) and real-time market data streaming.',
    requirements: 'Solid grasp of Java, Spring Boot, microservices architecture, and WebSocket protocols.',
    tags: ['groww', 'internship', 'bengaluru', 'fintech', 'trading', 'java', 'india'],
  },
  {
    companyName: 'Meesho',
    companyWebsite: 'https://meesho.io',
    industry: 'Social E-Commerce',
    title: 'SDE Intern - Growth & Discovery Platform',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: '₹65,000 - ₹85,000 / month',
    benefits: 'Work from anywhere in India, MacBook Pro, learning stipend, return offer path',
    applicationUrl: 'https://meesho.io/careers',
    deadline: new Date('2026-11-28'),
    description: 'Build recommendation engines, personalization algorithms, and supplier toolings for millions of tier-2 and tier-3 Indian shoppers.',
    requirements: 'Experience with Python, Java, or Golang. Knowledge of machine learning ranking models or backend API development.',
    tags: ['meesho', 'internship', 'bengaluru', 'remote', 'ecommerce', 'python', 'india'],
  },
  {
    companyName: 'Zerodha',
    companyWebsite: 'https://zerodha.com',
    industry: 'FinTech & Discount Brokerage',
    title: 'FOSS Engineering & Systems Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹75,000 / month',
    benefits: 'Open source ethos, calm work culture, healthcare coverage, book allowance',
    applicationUrl: 'https://zerodha.tech/careers',
    deadline: new Date('2026-12-01'),
    description: 'Build Kite trading platform tooling, open source financial libraries, and high-performance Postgres/Go backends with India’s largest stock broker.',
    requirements: 'Deep love for Free and Open Source Software (FOSS), Go, Python, Vue.js, or PostgreSQL. Active GitHub contributions.',
    tags: ['zerodha', 'internship', 'bengaluru', 'foss', 'golang', 'fintech', 'india'],
  },
  {
    companyName: 'InMobi',
    companyWebsite: 'https://inmobi.com',
    industry: 'AdTech & AI',
    title: 'Data Science & Software Engineering Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹50,000 - ₹70,000 / month',
    benefits: 'Mentorship from adtech pioneers, medical insurance, transport facilities',
    applicationUrl: 'https://inmobi.com/company/careers',
    deadline: new Date('2026-11-15'),
    description: 'Develop machine learning bidding engines processing billions of real-time ad auctions per second across mobile devices.',
    requirements: 'CS/Data Science background in India. Proficiency in Python, Spark, Java, and statistical modeling.',
    tags: ['inmobi', 'internship', 'bengaluru', 'adtech', 'data-science', 'ai', 'india'],
  },
  {
    companyName: 'MakeMyTrip',
    companyWebsite: 'https://makemytrip.com',
    industry: 'Travel & Hospitality Tech',
    title: 'Software Development Engineer Intern',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹45,000 - ₹65,000 / month',
    benefits: 'Travel discounts, cafeteria access, mentorship, return offer opportunity',
    applicationUrl: 'https://careers.makemytrip.com',
    deadline: new Date('2026-11-18'),
    description: 'Build dynamic flight and hotel search aggregators, pricing prediction models, and mobile booking experiences.',
    requirements: 'B.Tech/BE in CS or IT in India. Good knowledge of Java, Spring Boot, React, or Node.js.',
    tags: ['makemytrip', 'internship', 'gurugram', 'delhi-ncr', 'travel', 'java', 'india'],
  },
  {
    companyName: 'Dream11',
    companyWebsite: 'https://dream11.com',
    industry: 'SportsTech & Gaming',
    title: 'Software Engineering Intern - High Throughput Systems',
    type: OpportunityType.INTERNSHIP,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹75,000 - ₹1,00,000 / month',
    benefits: 'Sports stadium passes, gourmet food, health insurance, high PPO conversion',
    applicationUrl: 'https://careers.dream11.com',
    deadline: new Date('2026-11-20'),
    description: 'Build ultra-high-concurrency leaderboard engines handling 10M+ concurrent users during IPL match deadlines.',
    requirements: 'Strong CS fundamentals, experience with Java/Golang, Redis clustering, and distributed caching.',
    tags: ['dream11', 'internship', 'mumbai', 'sportstech', 'golang', 'distributed-systems', 'india'],
  },
  {
    companyName: 'Delhivery',
    companyWebsite: 'https://delhivery.com',
    industry: 'Logistics & Supply Chain',
    title: 'Data Science & SDE Intern - Route Optimization',
    type: OpportunityType.INTERNSHIP,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹45,000 - ₹65,000 / month',
    benefits: 'Health coverage, cafeteria, transport, PPO track',
    applicationUrl: 'https://delhivery.com/careers',
    deadline: new Date('2026-11-25'),
    description: 'Develop vehicle routing algorithms, automated sorting center robotics logic, and delivery SLA predictions across 18,000+ Indian pin codes.',
    requirements: 'Degree in CS/Operations Research/Math in India. Proficiency in Python, OR-Tools, and PostgreSQL.',
    tags: ['delhivery', 'internship', 'gurugram', 'delhi-ncr', 'logistics', 'python', 'india'],
  },

  // ==========================================
  // 3. TOP NATIONAL HACKATHONS (INSIDE INDIA)
  // ==========================================
  {
    companyName: 'Flipkart',
    companyWebsite: 'https://flipkart.com',
    industry: 'E-Commerce & Tech',
    title: 'Flipkart GRiD 6.0 - National Tech Hackathon & Campus Challenge',
    type: OpportunityType.HACKATHON,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹15,00,000+ Prize Pool + Direct PPI & SDE Interviews',
    benefits: 'Direct Pre-Placement Interviews (PPI) for SDE roles, national trophy, mentorship from Flipkart Tech leaders',
    applicationUrl: 'https://unstop.com/hackathons/flipkart-grid-60',
    deadline: new Date('2026-10-30'),
    description: 'Flipkart’s flagship engineering campus competition testing students across Generative AI, Robotics & Autonomous Delivery, Information Security, and Blockchain.',
    requirements: 'Open to all engineering students enrolled in B.Tech / B.E. / M.Tech across all Indian engineering colleges.',
    tags: ['hackathon', 'flipkart', 'grid', 'national', 'ai', 'robotics', 'india'],
  },
  {
    companyName: 'Walmart Global Tech',
    companyWebsite: 'https://walmart.com',
    industry: 'Retail Tech & AI',
    title: 'Walmart Sparkathon 2026 - Emerging Tech Challenge India',
    type: OpportunityType.HACKATHON,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹5,00,000+ Cash Prize + Summer Internship Offers',
    benefits: 'Fast-tracked Summer SDE Internships, mentorship from Walmart Silicon Valley & Bengaluru architects',
    applicationUrl: 'https://unstop.com/hackathons/walmart-sparkathon-2026',
    deadline: new Date('2026-11-05'),
    description: 'National hackathon empowering Indian students to reimagine digital commerce, supply chain visibility, and IoT store experiences.',
    requirements: 'Open to 2nd, 3rd, and 4th-year engineering students across Indian colleges.',
    tags: ['hackathon', 'walmart', 'sparkathon', 'bengaluru', 'iot', 'india'],
  },
  {
    companyName: 'Amazon',
    companyWebsite: 'https://amazon.jobs',
    industry: 'Cloud & AI',
    title: 'HackOn with Amazon 2026 - National Student Hackathon',
    type: OpportunityType.HACKATHON,
    location: 'Hyderabad, Telangana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹10,00,000 Prize Pool + Amazon SDE Intern PPIs',
    benefits: 'Direct interview track for Amazon SDE internships, AWS Cloud credits ($50,000), Amazon devices',
    applicationUrl: 'https://amazon.jobs/hackon-india',
    deadline: new Date('2026-11-15'),
    description: 'Flagship engineering hackathon by Amazon India challenging students to build scalable systems using AWS GenAI, serverless computing, and robotics.',
    requirements: 'Undergraduate and graduate engineering students enrolled in accredited Indian universities.',
    tags: ['hackathon', 'amazon', 'hackon', 'aws', 'hyderabad', 'india'],
  },
  {
    companyName: 'American Express',
    companyWebsite: 'https://americanexpress.com',
    industry: 'Financial Services',
    title: 'American Express CodeStreet India 2026',
    type: OpportunityType.HACKATHON,
    location: 'Gurugram, Haryana, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹4,00,000 Cash Prize + Direct Full-time/Intern Offers',
    benefits: 'Interview shortcuts for Technology Analyst roles, certificates, Amex swag kits',
    applicationUrl: 'https://unstop.com/hackathons/amex-codestreet-india-2026',
    deadline: new Date('2026-10-28'),
    description: 'National coding challenge and hackathon focused on AI in Fraud Risk, High Performance Payments, and Cloud Security.',
    requirements: 'B.Tech/BE/MCA students graduating in 2027 or 2028 in India.',
    tags: ['hackathon', 'amex', 'codestreet', 'fintech', 'gurugram', 'delhi-ncr', 'india'],
  },
  {
    companyName: 'Tata Group',
    companyWebsite: 'https://tata.com',
    industry: 'Conglomerate & Technology',
    title: 'Tata Imagination Challenge 2026',
    type: OpportunityType.HACKATHON,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹2,00,000 per winner + Tata Leadership Mentorship',
    benefits: 'Executive access to Tata Sons leaders, PPI opportunities across Tata Digital & TCS',
    applicationUrl: 'https://unstop.com/competitions/tata-imagination-challenge-2026',
    deadline: new Date('2026-10-20'),
    description: 'India’s largest campus innovation hackathon and case competition seeking creative solutions for digital India, sustainability, and AI.',
    requirements: 'All college students across India in any undergraduate or postgraduate discipline.',
    tags: ['hackathon', 'tata', 'innovation', 'mumbai', 'national', 'india'],
  },

  // ==========================================
  // 4. PREMIER RESEARCH & AI FELLOWSHIPS (INSIDE INDIA)
  // ==========================================
  {
    companyName: 'Microsoft Research',
    companyWebsite: 'https://microsoft.com/research',
    industry: 'Computer Science Research',
    title: 'Microsoft Research India (MSR) Research Fellow Program 2027',
    type: OpportunityType.FELLOWSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹12,00,000 - ₹15,00,000 / year (₹1,00,000 - ₹1,25,000 / month)',
    benefits: 'Direct co-authorship on top-tier conference papers (NeurIPS, ICML, SOSP, SIGCOMM), global PhD placement support',
    applicationUrl: 'https://microsoft.com/en-us/research/lab/microsoft-research-india/opportunities/',
    deadline: new Date('2026-12-01'),
    description: 'A 1 to 2 year prestigious research fellowship at MSR India in Bengaluru working alongside world-class scientists on Algorithms, AI, Systems, and Societal Impact.',
    requirements: 'B.Tech/M.Tech in CS/EE/Math in India graduating in 2027. Passion for rigorous scientific research.',
    tags: ['microsoft-research', 'fellowship', 'bengaluru', 'ai', 'systems', 'research', 'india'],
  },
  {
    companyName: 'Google Research',
    companyWebsite: 'https://research.google',
    industry: 'AI & Machine Learning Research',
    title: 'Google Research India - AI for Social Good Fellow',
    type: OpportunityType.FELLOWSHIP,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹1,20,000 / month stipend + Travel Grants',
    benefits: 'Google AI compute credits, publication mentorship, international conference travel grants',
    applicationUrl: 'https://research.google/locations/india/',
    deadline: new Date('2026-12-10'),
    description: 'Conduct foundational AI research applying Large Language Models, Multilingual AI, and Computer Vision to Healthcare and Agriculture in India.',
    requirements: 'Graduating seniors or master students with strong math, ML theory, and Python/JAX research portfolio.',
    tags: ['google-research', 'fellowship', 'bengaluru', 'ai-for-good', 'nlp', 'india'],
  },
  {
    companyName: 'Indian Institute of Science (IISc)',
    companyWebsite: 'https://iisc.ac.in',
    industry: 'Academic Research & Science',
    title: 'IISc Summer Research Fellowship (SRFP) 2027',
    type: OpportunityType.RESEARCH,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹15,000 - ₹25,000 / month stipend + Campus Hostel',
    benefits: 'Hostel accommodation on IISc lush campus, access to Supercomputing Education and Research Centre (SERC)',
    applicationUrl: 'https://iisc.ac.in/admissions/summer-research-fellowship-programme/',
    deadline: new Date('2026-11-30'),
    description: 'Prestigious 2-month summer research program at India’s #1 ranked research institution working in CSA, CDS, ECE, and AI labs.',
    requirements: 'Students in 2nd or 3rd year of B.E./B.Tech or 1st year M.Sc./M.Tech with outstanding academic standing (Top 10% in class).',
    tags: ['iisc', 'research', 'bengaluru', 'srfp', 'supercomputing', 'india'],
  },
  {
    companyName: 'IIT Bombay',
    companyWebsite: 'https://iitb.ac.in',
    industry: 'Higher Education & Technology Research',
    title: 'IIT Bombay Summer Research Internship Award 2027',
    type: OpportunityType.RESEARCH,
    location: 'Mumbai, Maharashtra, India',
    remoteType: RemoteType.ONSITE,
    salaryRange: '₹15,000 / month + Hostel Accommodation',
    benefits: 'Certificate signed by Dean R&D, full access to IITB research facilities and Powai campus',
    applicationUrl: 'https://iitb.ac.in/en/education/summer-internship',
    deadline: new Date('2026-11-28'),
    description: 'Work with IIT Bombay faculty on cutting-edge research in Quantum Computing, Artificial Intelligence, Robotics, and VLSI systems.',
    requirements: 'Pre-final year undergraduate or postgraduate engineering students across Indian colleges.',
    tags: ['iit-bombay', 'research', 'mumbai', 'summer-internship', 'quantum', 'india'],
  },
  {
    companyName: 'Wadhwani AI',
    companyWebsite: 'https://wadhwaniai.org',
    industry: 'AI for Social Good',
    title: 'AI Research & Data Science Intern',
    type: OpportunityType.RESEARCH,
    location: 'Bengaluru, Karnataka, India',
    remoteType: RemoteType.HYBRID,
    salaryRange: '₹40,000 - ₹60,000 / month',
    benefits: 'Direct social impact across maternal health and agriculture, GPU cluster access',
    applicationUrl: 'https://wadhwaniai.org/careers/',
    deadline: new Date('2026-11-20'),
    description: 'Build edge AI computer vision models and voice translation agents for frontline health workers and farmers across rural India.',
    requirements: 'CS/Data Science background in India with deep expertise in PyTorch, OpenCV, and model compression techniques (ONNX, TFLite).',
    tags: ['wadhwani-ai', 'research', 'bengaluru', 'ai', 'computer-vision', 'india'],
  },
  {
    companyName: 'GirlScript Foundation',
    companyWebsite: 'https://gssoc.girlscript.tech',
    industry: 'Open Source Community',
    title: 'GirlScript Summer of Code (GSSoC) 2027 Fellowship',
    type: OpportunityType.FELLOWSHIP,
    location: 'New Delhi, Delhi NCR, India',
    remoteType: RemoteType.REMOTE,
    salaryRange: 'Cash Prizes, Swag Kits & Hiring Partner Intros',
    benefits: 'Open source contribution certificates, 1-on-1 mentorship, placement referrals to sponsor tech companies',
    applicationUrl: 'https://gssoc.girlscript.tech',
    deadline: new Date('2026-11-15'),
    description: 'A 3-month open source fellowship program bringing beginners and experienced student developers across India together to build real-world software.',
    requirements: 'Open to all Indian college and university students passionate about Git, Web, App, and AI open source software.',
    tags: ['gssoc', 'fellowship', 'open-source', 'remote', 'delhi-ncr', 'india'],
  },
];

async function main() {
  console.log('🚀 Ingesting Comprehensive Inventory of Indian Tech Opportunities...');
  console.log(`Total target curated Indian opportunities: ${ALL_INDIAN_OPPORTUNITIES.length}`);

  let createdCount = 0;
  let updatedCount = 0;

  for (const opp of ALL_INDIAN_OPPORTUNITIES) {
    // 1. Get or create company
    let company = await prisma.company.findFirst({
      where: { name: { equals: opp.companyName, mode: 'insensitive' } },
    });

    if (!company) {
      company = await prisma.company.create({
        data: {
          name: opp.companyName,
          websiteUrl: opp.companyWebsite,
          industry: opp.industry,
          description: `Leading organization with top-tier technology operations in India.`,
        },
      });
    }

    // 2. Upsert opportunity
    const existing = await prisma.opportunity.findFirst({
      where: {
        companyId: company.id,
        title: opp.title,
      },
    });

    if (!existing) {
      await prisma.opportunity.create({
        data: {
          title: opp.title,
          type: opp.type,
          companyId: company.id,
          location: opp.location,
          remoteType: opp.remoteType,
          salaryRange: opp.salaryRange,
          benefits: opp.benefits,
          applicationUrl: opp.applicationUrl,
          deadline: opp.deadline,
          description: opp.description,
          requirements: opp.requirements,
          tags: opp.tags,
          isActive: true,
          isArchived: false,
        },
      });
      createdCount++;
    } else {
      await prisma.opportunity.update({
        where: { id: existing.id },
        data: {
          location: opp.location,
          salaryRange: opp.salaryRange,
          benefits: opp.benefits,
          applicationUrl: opp.applicationUrl,
          deadline: opp.deadline,
          description: opp.description,
          requirements: opp.requirements,
          tags: opp.tags,
          isActive: true,
          isArchived: false,
        },
      });
      updatedCount++;
    }
  }

  console.log(`\n✓ Opportunity Ingestion Completed:`);
  console.log(`- Created: ${createdCount}`);
  console.log(`- Updated: ${updatedCount}`);

  // Summary Metrics
  const totalCount = await prisma.opportunity.count();
  const hackathons = await prisma.opportunity.count({ where: { type: OpportunityType.HACKATHON } });
  const fellowships = await prisma.opportunity.count({ where: { type: OpportunityType.FELLOWSHIP } });
  const internships = await prisma.opportunity.count({ where: { type: OpportunityType.INTERNSHIP } });
  const research = await prisma.opportunity.count({ where: { type: OpportunityType.RESEARCH } });

  console.log('\n📊 Database Inventory of Indian Opportunities:');
  console.log(`- 💼 Internships: ${internships}`);
  console.log(`- 🏆 Hackathons: ${hackathons}`);
  console.log(`- 🎓 Fellowships: ${fellowships}`);
  console.log(`- 🔬 Research Programs: ${research}`);
  console.log(`- 🌟 Total Indian Opportunities: ${totalCount}`);

  // Trigger AI enrichment on any pending newly added items
  console.log('\n🧠 Triggering AI Enrichment Pipeline for all pending Indian opportunities...');
  const enrichResult = await EnrichmentEngine.drainAllPending();
  console.log(`✓ AI Enrichment complete! Processed: ${enrichResult.processed}, Success: ${enrichResult.success}, Failed: ${enrichResult.failed}`);
}

main()
  .then(() => {
    console.log('\n🎉 All Indian internships, fellowships, hackathons & research programs successfully ingested & enriched!');
    process.exit(0);
  })
  .catch((err) => {
    console.error('Fatal error during ingestion:', err);
    process.exit(1);
  });
